export const validCategoriesOD = [
    "Filtro Aceite Spin On",
    "Filtro Aceite Elemento",
    "Filtro Aceite Centrifugo",
    "Filtro Aire Cilíndrico",
    "Filtro Combustible In-Line / In-Tank / Regulador / Modulo",
    "Filtro Combustible Spin On",
    "Filtro Combustible Cartucho / CAV",
    "Filtro Secante Spin On",
    "Filtro Hidraulico Spin On",
    "Filtro Hidraulico Elemento",
    "Filtro Refrigerante Spin On",
];

export const validCategoriesH = [
    "Filtro Aceite Spin On",
    "Filtro Aceite Elemento",
    "Filtro Aceite Centrifugo",
    "Filtro Aire Panel",
    "Filtro Aire Cilíndrico",
    "Filtro Combustible In-Line / In-Tank / Regulador / Modulo",
    "Filtro Secante Spin On",
    "Filtro Combustible Cartucho / CAV",
    "Filtro Cabina Panel",
    "Filtro Secante Spin On",
    "Filtro Hidraulico Elemento",
    "Filtro Hidraulico Vaso",
    "Filtro Refrigerante Spin On",
];

export const validCategoriesTH = [
    "Filtro Aceite Spin On",
    "Filtro Combustible Spin On",
    "Filtro Secante Spin On",
    "Filtro Hidraulico Spin On",
    "Filtro Refrigerante Spin On",
];

export const validCategoriesGSOD = ["Filtro Aceite Spin On"];

export const validCategoriesDiametroExterno = [
    "Filro Aceite Spin On",
    "Filtro Aceite Elemento",
    "Filtro Aceite Centrifugo",
    "Filtro Aire Cilíndrico",
    "Filtro Refrigerante Spin On",
    "Filtro Aire Toroide Rect. o Elip",
];

export const validCategoriesDiametroInterno = [
    "Filtro Aire Toroide Rect. o Elip",
    "Filtro Aire Cilíndrico",
    "Filtro Aceite Elemento",
    "Filtro Combustible Cartucho / CAV",
];

export const validCategoriesDiametroRosca = [
    "Filtro Refrigerante Spin On",
    "Filtro Hidraulico Spin On",
    "Filtro Hidraulico Spin",
    "Filtro Secante Spin On",
    "Filtro Combustible Spin On",
];

export const validCategoriesLonguitud = [
    "Filtro Aire Panel",
    "Filtro Aire Toroide Rect. o Elip.",
    "Filtro Cabina Panel",
];

export const brands = [
    "ACURA",
    "ALFA ROMEO",
    "AMC",
    "ARO",
    "ASIA",
    "AUDI",
    "BMW",
    "CHANGAN",
    "CHERY",
    "CHEVROLET",
    "CHRYSLER",
    "CINASCAR",
    "CITROEN",
    "DACIA",
    "DAEWOO",
    "DAIHATSU",
    "DODGE",
    "DONGFENG",
    "FIAT",
    "FORD",
    "GEELY",
    "GREAT WALL",
    "HAIMA",
    "HONDA",
    "HUMMER",
    "HYUNDAI",
    "ISUZU",
    "JAC",
    "JEEP",
    "JMC",
    "KIA",
    "LADA",
    "LAND ROVER",
    "LEXUS",
    "MAZDA",
    "MERCEDES BENZ",
    "MINI",
    "MITSUBISHI",
    "NISSAN",
    "PEUGEOT",
    "RENAULT",
    "SEAT",
    "SKODA",
    "SUBARU",
    "SUZUKI",
    "TATA",
    "TOYOTA",
    "VENIRAUTO",
    "VOLKSWAGEN",
    "VOLVO",
];

export const modelList = [
    { brand: "ACURA", model: "INTEGRA" },
    { brand: "ACURA", model: "VIGOR" },
    { brand: "ALFA ROMEO", model: "16 Ti" },
    { brand: "ALFA ROMEO", model: "156T" },
    { brand: "AMC", model: "HORNET" },
    { brand: "AMC", model: "JAVELIN" },
    { brand: "ARO", model: "BUFFALO" },
    { brand: "ARO", model: "DAKTARI" },
    { brand: "ARO", model: "DAKTARI" },
    { brand: "ARO", model: "RANGER" },
    { brand: "ARO", model: "RANGER" },
    { brand: "ARO", model: "RINO PI:K-P" },
    { brand: "ASIA", model: "TOWNER" },
    { brand: "AUDI", model: "90" },
    { brand: "AUDI", model: "100" },
    { brand: "AUDI", model: "A3" },
    { brand: "AUDI", model: "A3" },
    { brand: "AUDI", model: "A3" },
    { brand: "AUDI", model: "A4  " },
    { brand: "AUDI", model: "A4  " },
    { brand: "AUDI", model: "A4 " },
    { brand: "AUDI", model: "A4 " },
    { brand: "AUDI", model: "A6 " },
    { brand: "AUDI", model: "A6 " },
    { brand: "AUDI", model: "A6  " },
    { brand: "AUDI", model: "S4" },
    { brand: "AUDI", model: "RS4" },
    { brand: "AUDI", model: "S6" },
    { brand: "AUDI", model: "RS6" },
    { brand: "AUDI", model: "TT" },
    { brand: "BMW", model: "318i" },
    { brand: "BMW", model: "320i" },
    { brand: "BMW", model: "320i" },
    { brand: "BMW", model: "323i" },
    { brand: "BMW", model: "325i" },
    { brand: "BMW", model: "325i" },
    { brand: "BMW", model: "328i" },
    { brand: "BMW", model: "525i" },
    { brand: "BMW", model: "525i" },
    { brand: "BMW", model: "525i" },
    { brand: "BMW", model: "528i" },
    { brand: "BMW", model: "530i" },
    { brand: "BMW", model: "735i" },
    { brand: "BMW", model: "X3" },
    { brand: "CHANGAN", model: "ALSVIN SI:C/UTO" },
    { brand: "CHANGAN", model: "CS15" },
    { brand: "CHANGAN", model: "C35 PLUS" },
    { brand: "CHANGAN", model: "KAICENE F:0/HUNTER" },
    { brand: "CHERY", model: "AAUCA A1" },
    { brand: "CHERY", model: "AAUCA S15" },
    { brand: "CHERY", model: "GRAN: TIGER 4X2" },
    { brand: "CHERY", model: "GRAN: TIGER 4X4" },
    { brand: "CHERY", model: "ORINOCO" },
    { brand: "CHERY", model: "QQ" },
    { brand: "CHERY", model: "TIGGO" },
    { brand: "CHERY", model: "X1" },
    { brand: "CHEVROLET", model: "ATRA CONFORT" },
    { brand: "CHEVROLET", model: "	ATRA CONFORT" },
    { brand: "CHEVROLET", model: "	ATRA ELEGANCE" },
    { brand: "CHEVROLET", model: "	ATRA COUPE" },
    { brand: "CHEVROLET", model: "	ATRA TURBO" },
    { brand: "CHEVROLET", model: "AVALANCHE" },
    { brand: "CHEVROLET", model: "AVEO" },
    { brand: "CHEVROLET", model: "AEO LS" },
    { brand: "CHEVROLET", model: "AEO LT" },
    { brand: "CHEVROLET", model: "BLAZER" },
    { brand: "CHEVROLET", model: "BLAZER" },
    { brand: "CHEVROLET", model: "BLAZER" },
    { brand: "CHEVROLET", model: "CAMARO 1:t-en" },
    { brand: "CHEVROLET", model: "CAMARO 2:d-en" },
    { brand: "CHEVROLET", model: "CAMARO 2:d-en" },
    { brand: "CHEVROLET", model: "CAMARO 3:d-en" },
    { brand: "CHEVROLET", model: "CAMARO 4t:-Gn I" },
    { brand: "CHEVROLET", model: "CAMARO 4t:-Gn I" },
    { brand: "CHEVROLET", model: "CAMARO 4t:-Gn II" },
    { brand: "CHEVROLET", model: "CAMARO 4t:-Gn II" },
    { brand: "CHEVROLET", model: "CAPRICE" },
    { brand: "CHEVROLET", model: "CAPRICE" },
    { brand: "CHEVROLET", model: "CAPRICE" },
    { brand: "CHEVROLET", model: "CAPRICE" },
    { brand: "CHEVROLET", model: "CAPRICE" },
    { brand: "CHEVROLET", model: "CAPRICE" },
    { brand: "CHEVROLET", model: "CAPRICE" },
    { brand: "CHEVROLET", model: "CAPRICE" },
    { brand: "CHEVROLET", model: "CAPTIVA" },
    { brand: "CHEVROLET", model: "CAVALIER" },
    { brand: "CHEVROLET", model: "CAVALIER" },
    { brand: "CHEVROLET", model: "CVALIER  Z24" },
    { brand: "CHEVROLET", model: "CELEBRITY" },
    { brand: "CHEVROLET", model: "CELEBRITY" },
    { brand: "CHEVROLET", model: "CENTURY" },
    { brand: "CHEVROLET", model: "CENTURY" },
    { brand: "CHEVROLET", model: "CENTURY" },
    { brand: "CHEVROLET", model: "CENTURY" },
    { brand: "CHEVROLET", model: "CENTURY" },
    { brand: "CHEVROLET", model: "CHEVELLE" },
    { brand: "CHEVROLET", model: "CHEVELLE" },
    { brand: "CHEVROLET", model: "CHEVELLE" },
    { brand: "CHEVROLET", model: "CHEVELLE" },
    { brand: "CHEVROLET", model: "CHEVETTE" },
    { brand: "CHEVROLET", model: "CHEVETTE" },
    { brand: "CHEVROLET", model: "CHEVY  " },
    { brand: "CHEVROLET", model: "COLORADO " },
    { brand: "CHEVROLET", model: "COLORADO" },
    { brand: "CHEVROLET", model: "CORSA " },
    { brand: "CHEVROLET", model: "CORSA" },
    { brand: "CHEVROLET", model: "CORSA" },
    { brand: "CHEVROLET", model: "CORSA" },
    { brand: "CHEVROLET", model: "CORSICA" },
    { brand: "CHEVROLET", model: "CORVETTE" },
    { brand: "CHEVROLET", model: "CORVETTE" },
    { brand: "CHEVROLET", model: "CORVETTE" },
    { brand: "CHEVROLET", model: "CRUZE" },
    { brand: "CHEVROLET", model: "EPICA" },
    { brand: "CHEVROLET", model: "ESTEEM" },
    { brand: "CHEVROLET", model: "EXPRES: CRGO 1500" },
    { brand: "CHEVROLET", model: "EXPRES: PSSENGER VAN" },
    { brand: "CHEVROLET", model: "GC YUKON" },
    { brand: "CHEVROLET", model: "GC YUKON" },
    { brand: "CHEVROLET", model: "GAND AM" },
    { brand: "CHEVROLET", model: "GAND AM" },
    { brand: "CHEVROLET", model: "GAND BLAZER" },
    { brand: "CHEVROLET", model: "GAND BLAZER" },
    { brand: "CHEVROLET", model: "GAND BLAZER" },
    { brand: "CHEVROLET", model: "GAND BLAZER" },
    { brand: "CHEVROLET", model: "GRAN: BAZER Z71" },
    { brand: "CHEVROLET", model: "GAND VITARA" },
    { brand: "CHEVROLET", model: "GAND VITARA" },
    { brand: "CHEVROLET", model: "GAND VITARA" },
    { brand: "CHEVROLET", model: "GRAN: VTARA XL7" },
    { brand: "CHEVROLET", model: "IMPALA" },
    { brand: "CHEVROLET", model: "IMPALA" },
    { brand: "CHEVROLET", model: "IMPALA" },
    { brand: "CHEVROLET", model: "IMPALA" },
    { brand: "CHEVROLET", model: "IMPALA" },
    { brand: "CHEVROLET", model: "IMPALA" },
    { brand: "CHEVROLET", model: "IMPALA" },
    { brand: "CHEVROLET", model: "IMPALA" },
    { brand: "CHEVROLET", model: "IMPALA" },
    { brand: "CHEVROLET", model: "JIMNY" },
    { brand: "CHEVROLET", model: "LUMINA" },
    { brand: "CHEVROLET", model: "LUMINA" },
    { brand: "CHEVROLET", model: "LMINA APV" },
    { brand: "CHEVROLET", model: "LMINA APV" },
    { brand: "CHEVROLET", model: "LUV" },
    { brand: "CHEVROLET", model: "LUV" },
    { brand: "CHEVROLET", model: "LUV" },
    { brand: "CHEVROLET", model: "	LUV :D-AX" },
    { brand: "CHEVROLET", model: "	LUV :D-AX" },
    { brand: "CHEVROLET", model: "MALIBU" },
    { brand: "CHEVROLET", model: "MALIBU" },
    { brand: "CHEVROLET", model: "MALIBU" },
    { brand: "CHEVROLET", model: "MALIBU" },
    { brand: "CHEVROLET", model: "MALIBU" },
    { brand: "CHEVROLET", model: "MALIBU" },
    { brand: "CHEVROLET", model: "MERIVA" },
    { brand: "CHEVROLET", model: "MONTANA" },
    { brand: "CHEVROLET", model: "MNTE CARLO" },
    { brand: "CHEVROLET", model: "MNTE CARLO" },
    { brand: "CHEVROLET", model: "MNTE CARLO" },
    { brand: "CHEVROLET", model: "MNTE CARLO" },
    { brand: "CHEVROLET", model: "MNTE CARLO" },
    { brand: "CHEVROLET", model: "MNTE CARLO" },
    { brand: "CHEVROLET", model: "MONZA" },
    { brand: "CHEVROLET", model: "MONZA" },
    { brand: "CHEVROLET", model: "NOVA" },
    { brand: "CHEVROLET", model: "NOVA" },
    { brand: "CHEVROLET", model: "NOVA" },
    { brand: "CHEVROLET", model: "NOVA" },
    { brand: "CHEVROLET", model: "NOVA" },
    { brand: "CHEVROLET", model: "NOVA" },
    { brand: "CHEVROLET", model: "NOVA" },
    { brand: "CHEVROLET", model: "NOVA" },
    { brand: "CHEVROLET", model: "ORLANDO" },
    { brand: "CHEVROLET", model: "OPTRA" },
    { brand: "CHEVROLET", model: "OPTRA" },
    { brand: "CHEVROLET", model: "	PIC:-U C10" },
    { brand: "CHEVROLET", model: "	PIC:-U C10" },
    { brand: "CHEVROLET", model: "	PIC:-U C10" },
    { brand: "CHEVROLET", model: "	PIC:-U C10" },
    { brand: "CHEVROLET", model: "	PIC:-U C1500" },
    { brand: "CHEVROLET", model: "	PIC:-U C1500" },
    { brand: "CHEVROLET", model: "	PIC:-U C1500" },
    { brand: "CHEVROLET", model: "	PIC:-U C1500" },
    { brand: "CHEVROLET", model: "	PIC:-U C1500" },
    { brand: "CHEVROLET", model: "	PICK-UP :-100 CHEYENNE" },
    { brand: "CHEVROLET", model: "	PICK-UP :-100 CHEYENNE" },
    { brand: "CHEVROLET", model: "	PICK-UP :-100 CHEYENNE" },
    { brand: "CHEVROLET", model: "	PICK-UP :-100 CHEYENNE" },
    { brand: "CHEVROLET", model: "	PICK-UP :-100 CHEYENNE" },
    { brand: "CHEVROLET", model: "	PIC:-U  S10" },
    { brand: "CHEVROLET", model: "SAFARI" },
    { brand: "CHEVROLET", model: "SILVERADO" },
    { brand: "CHEVROLET", model: "SILVERADO" },
    { brand: "CHEVROLET", model: "SILVERADO" },
    { brand: "CHEVROLET", model: "SILVERADO" },
    { brand: "CHEVROLET", model: "SILVERADO" },
    { brand: "CHEVROLET", model: "SPARK" },
    { brand: "CHEVROLET", model: "SUBURBAN" },
    { brand: "CHEVROLET", model: "SUBURBAN" },
    { brand: "CHEVROLET", model: "SUNFIRE" },
    { brand: "CHEVROLET", model: "SNFIRE GT" },
    { brand: "CHEVROLET", model: "SPER CARRY" },
    { brand: "CHEVROLET", model: "SWIFT" },
    { brand: "CHEVROLET", model: "SWIFT" },
    { brand: "CHEVROLET", model: "SWIFT" },
    { brand: "CHEVROLET", model: "TAHOE" },
    { brand: "CHEVROLET", model: "TRAILBLAZER" },
    { brand: "CHEVROLET", model: "TRAILBLAZER" },
    { brand: "CHEVROLET", model: "TRAILBLAZER" },
    { brand: "CHEVROLET", model: "VITARA" },
    { brand: "CHEVROLET", model: "VITARA" },
    { brand: "CHEVROLET", model: "WGON R+" },
    { brand: "CHRYSLER", model: "300C" },
    { brand: "CHRYSLER", model: "300M" },
    { brand: "CHRYSLER", model: "CIRRUS" },
    { brand: "CHRYSLER", model: "L BARON" },
    { brand: "CHRYSLER", model: "L BARON" },
    { brand: "CHRYSLER", model: "NEON" },
    { brand: "CHRYSLER", model: "NEON" },
    { brand: "CHRYSLER", model: "NEON" },
    { brand: "CHRYSLER", model: "NW YORKER" },
    { brand: "CHRYSLER", model: "NW YORKER" },
    { brand: "CHRYSLER", model: "P CRUISER" },
    { brand: "CHRYSLER", model: "P CRUISER" },
    { brand: "CHRYSLER", model: "SEBRING" },
    { brand: "CHRYSLER", model: "VALIANT" },
    { brand: "CHRYSLER", model: "VALIANT" },
    { brand: "CHRYSLER", model: "VALIANT" },
    { brand: "CHRYSLER", model: "VALIANT" },
    { brand: "CHRYSLER", model: "	VAN TO:N-OUNTRY" },
    { brand: "CHRYSLER", model: "	VAN TO:N-OUNTRY" },
    { brand: "CHRYSLER", model: "	VAN TO:N-OUNTRY" },
    { brand: "CHRYSLER", model: "	VAN TO:N-OUNTRY" },
    { brand: "CHRYSLER", model: "	VAN TO:N-OUNTRY" },
    { brand: "CHRYSLER", model: "	VAN TO:N-OUNTRY" },
    { brand: "CHRYSLER", model: "	BD FLYER" },
    { brand: "CINASCAR", model: "	CHAN: DBLE CABINA" },
    { brand: "CINASCAR", model: "	CHAN: PCK UP" },
    { brand: "CINASCAR", model: "	HFEI  LOBO" },
    { brand: "CINASCAR", model: "	HFEI XINYI" },
    { brand: "CINASCAR", model: "	HFEI ZHONGHIL" },
    { brand: "CINASCAR", model: "	SAIC WULING CARG: PNEL VAN" },
    { brand: "CINASCAR", model: "	SAIC WULING SUPE: VN CONFORT" },
    { brand: "CINASCAR", model: "	ZTYE NOMAD" },
    { brand: "CINASCAR", model: "	ZTYE NOMAD" },
    { brand: "CINASCAR", model: "	ZX AUT: GAND TIGER" },
    { brand: "CITROEN", model: "BERLINGO" },
    { brand: "CITROEN", model: "BERLINGO" },
    { brand: "CITROEN", model: "C VTR" },
    { brand: "CITROEN", model: "C3" },
    { brand: "CITROEN", model: "C3" },
    { brand: "CITROEN", model: "C BERLINA" },
    { brand: "CITROEN", model: "C BERLINA" },
    { brand: "CITROEN", model: "	C4: CUPE  VTS" },
    { brand: "CITROEN", model: "C5" },
    { brand: "CITROEN", model: "C5" },
    { brand: "CITROEN", model: "PCASSO XSARA" },
    { brand: "DACIA", model: "BERLINA" },
    { brand: "DACIA", model: "BERLINA" },
    { brand: "DACIA", model: "BREAK" },
    { brand: "DACIA", model: "BREAK" },
    { brand: "DACIA", model: "NOVA" },
    { brand: "DACIA", model: "NOVA" },
    { brand: "DAEWOO", model: "CIELO" },
    { brand: "DAEWOO", model: "DAMAS" },
    { brand: "DAEWOO", model: "ESPERO" },
    { brand: "DAEWOO", model: "LABO" },
    { brand: "DAEWOO", model: "LANOS" },
    { brand: "DAEWOO", model: "LANOS" },
    { brand: "DAEWOO", model: "LEGANZA" },
    { brand: "DAEWOO", model: "MATIZ" },
    { brand: "DAEWOO", model: "NUBIRA" },
    { brand: "DAEWOO", model: "NUBIRA" },
    { brand: "DAEWOO", model: "PRINCE" },
    { brand: "DAEWOO", model: "RCER CAB." },
    { brand: "DAEWOO", model: "RACER" },
    { brand: "DAEWOO", model: "SPER SALOON" },
    { brand: "DAEWOO", model: "SPER SALOON" },
    { brand: "DAEWOO", model: "TACUMA" },
    { brand: "DAEWOO", model: "TACUMA" },
    { brand: "DAEWOO", model: "TICO" },
    { brand: "DAIHATSU", model: "APPLAUSE" },
    { brand: "DAIHATSU", model: "CHARADE" },
    { brand: "DAIHATSU", model: "FEROZA" },
    { brand: "DAIHATSU", model: "TERIOS" },
    { brand: "DAIHATSU", model: "	TERIOS  :E-O" },
    { brand: "DODGE", model: "ASPEN" },
    { brand: "DODGE", model: "ASPEN" },
    { brand: "DODGE", model: "	BRIS: (ccent)" },
    { brand: "DODGE", model: "	BRIS: (etz)" },
    { brand: "DODGE", model: "CALIBER" },
    { brand: "DODGE", model: "CALIBER" },
    { brand: "DODGE", model: "CARAVAN" },
    { brand: "DODGE", model: "CARAVAN" },
    { brand: "DODGE", model: "DAKOTA" },
    { brand: "DODGE", model: "DAKOTA" },
    { brand: "DODGE", model: "DAKOTA" },
    { brand: "DODGE", model: "DART" },
    { brand: "DODGE", model: "DART" },
    { brand: "DODGE", model: "DAYTONA" },
    { brand: "DODGE", model: "DURANGO" },
    { brand: "DODGE", model: "DURANGO" },
    { brand: "DODGE", model: "DURANGO" },
    { brand: "DODGE", model: "FORZA" },
    { brand: "DODGE", model: "GAND CARAVAN" },
    { brand: "DODGE", model: "INTREPID" },
    { brand: "DODGE", model: "INTREPID" },
    { brand: "DODGE", model: "MXI WAGON" },
    { brand: "DODGE", model: "RM 2500" },
    { brand: "DODGE", model: "RM 2500" },
    { brand: "DODGE", model: "RM 2500" },
    { brand: "DODGE", model: "RM 2500" },
    { brand: "DODGE", model: "RM 3500" },
    { brand: "DODGE", model: "SPIRIT" },
    { brand: "DODGE", model: "STEALTH" },
    { brand: "DODGE", model: "STRATUS" },
    { brand: "DODGE", model: "STRATUS" },
    { brand: "DODGE", model: "VIPER" },
    { brand: "DODGE", model: "VIPER" },
    { brand: "DONGFENG", model: "PICK U: D 4X4" },
    { brand: "DONGFENG", model: "S30" },
    { brand: "DONGFENG", model: "	RCH P11" },
    { brand: "DONGFENG", model: "RCH 6" },
    { brand: "DONGFENG", model: "RIC: 6Diesel" },
    { brand: "FIAT", model: "124" },
    { brand: "FIAT", model: "125" },
    { brand: "FIAT", model: "128" },
    { brand: "FIAT", model: "131" },
    { brand: "FIAT", model: "132" },
    { brand: "FIAT", model: "147" },
    { brand: "FIAT", model: "147" },
    { brand: "FIAT", model: "AGO TREKKING" },
    { brand: "FIAT", model: "BRAVA" },
    { brand: "FIAT", model: "CONOS CVT" },
    { brand: "FIAT", model: "CONOS MT" },
    { brand: "FIAT", model: "FIORINO" },
    { brand: "FIAT", model: "FIORINO" },
    { brand: "FIAT", model: "FIORINO" },
    { brand: "FIAT", model: "FIORINO" },
    { brand: "FIAT", model: "FIORINO" },
    { brand: "FIAT", model: "FLLBACK Diesel" },
    { brand: "FIAT", model: "IDEA HLX / AVENTUR: /SKY" },
    { brand: "FIAT", model: "MAREA EL: / WEEKEND" },
    { brand: "FIAT", model: "MIRAFIORI" },
    { brand: "FIAT", model: "MIRAFIORI" },
    { brand: "FIAT", model: "MBI TREKKING" },
    { brand: "FIAT", model: "PALIO" },
    { brand: "FIAT", model: "PALIO ADVENTURE/H:X/EEKEND" },
    { brand: "FIAT", model: "PLIO MPI" },
    { brand: "FIAT", model: "PLIO FIRE" },
    { brand: "FIAT", model: "PICK-U: SRADA TREKKING" },
    { brand: "FIAT", model: "PICK-UP STRAD: TEKKING MPI" },
    { brand: "FIAT", model: "PREMIO" },
    { brand: "FIAT", model: "PREMIO" },
    { brand: "FIAT", model: "PREMIO" },
    { brand: "FIAT", model: "PUNTO" },
    { brand: "FIAT", model: "REGATA" },
    { brand: "FIAT", model: "REGATA" },
    { brand: "FIAT", model: "REGATA" },
    { brand: "FIAT", model: "RITMO" },
    { brand: "FIAT", model: "RITMO" },
    { brand: "FIAT", model: "RITMO" },
    { brand: "FIAT", model: "SELECTA" },
    { brand: "FIAT", model: "SIENA" },
    { brand: "FIAT", model: "SIENA" },
    { brand: "FIAT", model: "SIENA" },
    { brand: "FIAT", model: "SENA FIRE" },
    { brand: "FIAT", model: "SENA HLX" },
    { brand: "FIAT", model: "SPAZIO" },
    { brand: "FIAT", model: "SPAZIO" },
    { brand: "FIAT", model: "STYLO" },
    { brand: "FIAT", model: "TEMPRA" },
    { brand: "FIAT", model: "TEMPRA" },
    { brand: "FIAT", model: "TEMPRA" },
    { brand: "FIAT", model: "TEMPRA" },
    { brand: "FIAT", model: "TIPO" },
    { brand: "FIAT", model: "TUCAN" },
    { brand: "FIAT", model: "UNO" },
    { brand: "FIAT", model: "UNO" },
    { brand: "FIAT", model: "UNO" },
    { brand: "FIAT", model: "UNO" },
    { brand: "FIAT", model: "UNO" },
    { brand: "FIAT", model: "UO FIRE" },
    { brand: "FORD", model: "AEROSTAR" },
    { brand: "FORD", model: "BRONCO" },
    { brand: "FORD", model: "BRONCO" },
    { brand: "FORD", model: "BRONCO" },
    { brand: "FORD", model: "BRONCO" },
    { brand: "FORD", model: "BRONCO" },
    { brand: "FORD", model: "BONCO SPORT" },
    { brand: "FORD", model: "BRONCO" },
    { brand: "FORD", model: "BRONCO" },
    { brand: "FORD", model: "BRONCO" },
    { brand: "FORD", model: "CONQUISTADOR" },
    { brand: "FORD", model: "CONQUISTADOR" },
    { brand: "FORD", model: "CONTINENTAL" },
    { brand: "FORD", model: "CORCEL GHIA : DL REY" },
    { brand: "FORD", model: "CORCEL II : DL REY" },
    { brand: "FORD", model: "COUGAR" },
    { brand: "FORD", model: "COUGAR" },
    { brand: "FORD", model: "COUGAR" },
    { brand: "FORD", model: "COWN VICTORIA" },
    { brand: "FORD", model: "COWN VICTORIA" },
    { brand: "FORD", model: "ECONOLINE" },
    { brand: "FORD", model: "ECONOLINE" },
    { brand: "FORD", model: "ECOSPORT" },
    { brand: "FORD", model: "ECOSPORT" },
    { brand: "FORD", model: "ECOSPORT" },
    { brand: "FORD", model: "ESCAPE" },
    { brand: "FORD", model: "ESCAPE" },
    { brand: "FORD", model: "	ESCORT/ORIO: (16)" },
    { brand: "FORD", model: "ESCORT" },
    { brand: "FORD", model: "EXCURSION" },
    { brand: "FORD", model: "EXPEDITION" },
    { brand: "FORD", model: "EXPEDITION" },
    { brand: "FORD", model: "EXPEDITION" },
    { brand: "FORD", model: "EXPEDITION" },
    { brand: "FORD", model: "EXPEDITION" },
    { brand: "FORD", model: "EXPLORER" },
    { brand: "FORD", model: "EXPLORER" },
    { brand: "FORD", model: "EXPLORER" },
    { brand: "FORD", model: "EXPLORER" },
    { brand: "FORD", model: "	EPLORER SPORT" },
    { brand: "FORD", model: "EXPLORER" },
    { brand: "FORD", model: "EPLORER SPORT" },
    { brand: "FORD", model: "EXPLORER" },
    { brand: "FORD", model: "EXPLORER" },
    { brand: "FORD", model: "	EXPLORE: SORT TRAC" },
    { brand: "FORD", model: "EXPLORER" },
    { brand: "FORD", model: "EXPLORER" },
    { brand: "FORD", model: "EPLORER ST" },
    { brand: "FORD", model: ":F-00" },
    { brand: "FORD", model: ":F-00" },
    { brand: "FORD", model: ":F-00" },
    { brand: "FORD", model: ":F-00" },
    { brand: "FORD", model: ":F-50" },
    { brand: "FORD", model: ":F-50" },
    { brand: "FORD", model: ":F-50" },
    { brand: "FORD", model: ":F-50" },
    { brand: "FORD", model: ":F-50" },
    { brand: "FORD", model: ":F-50" },
    { brand: "FORD", model: ":F-50" },
    { brand: "FORD", model: ":F-50" },
    { brand: "FORD", model: ":F-50" },
    { brand: "FORD", model: ":F-50" },
    { brand: "FORD", model: "	F-150  FX4 : Hrley Davidson" },
    { brand: "FORD", model: "	:-10  RAPTOR" },
    { brand: "FORD", model: "	F-25: Sper Duty" },
    { brand: "FORD", model: ":F-50" },
    { brand: "FORD", model: ":F-50" },
    { brand: "FORD", model: ":F-50" },
    { brand: "FORD", model: ":F-50" },
    { brand: "FORD", model: ":F-50" },
    { brand: "FORD", model: ":F-50" },
    { brand: "FORD", model: ":F-50" },
    { brand: "FORD", model: ":F-50" },
    { brand: "FORD", model: ":F-50" },
    { brand: "FORD", model: "	F-35: Sper Duty" },
    { brand: "FORD", model: "FAIRLANE" },
    { brand: "FORD", model: "	FAIRLANE 50: /GALAXIE" },
    { brand: "FORD", model: "	FAIRLANE 50: /GALAXIE" },
    { brand: "FORD", model: "FAIRMONT" },
    { brand: "FORD", model: "FALCON" },
    { brand: "FORD", model: "FESTIVA" },
    { brand: "FORD", model: "FESTIVA" },
    { brand: "FORD", model: "FIESTA" },
    { brand: "FORD", model: "FIESTA" },
    { brand: "FORD", model: "FIESTA" },
    { brand: "FORD", model: "	FESTA POWER" },
    { brand: "FORD", model: "	FESTA MAX" },
    { brand: "FORD", model: "	FESTA MOVE" },
    { brand: "FORD", model: "	FESTA TITANIUM" },
    { brand: "FORD", model: "FOCUS" },
    { brand: "FORD", model: "FOCUS" },
    { brand: "FORD", model: "FUSION" },
    { brand: "FORD", model: "FUTURA" },
    { brand: "FORD", model: "GRANADA" },
    { brand: "FORD", model: "	GAND MARQUIS" },
    { brand: "FORD", model: "	GAND MARQUIS" },
    { brand: "FORD", model: "KA" },
    { brand: "FORD", model: "LASER" },
    { brand: "FORD", model: "LASER" },
    { brand: "FORD", model: "	LINCOL: TWN CAR" },
    { brand: "FORD", model: "	LINCOL: TWN CAR" },
    { brand: "FORD", model: "LTD" },
    { brand: "FORD", model: "LTD" },
    { brand: "FORD", model: "LTD" },
    { brand: "FORD", model: "MAVERICK" },
    { brand: "FORD", model: "MAVERICK" },
    { brand: "FORD", model: "MAVERICK" },
    { brand: "FORD", model: "MUSTANG" },
    { brand: "FORD", model: "MUSTANG" },
    { brand: "FORD", model: "MUSTANG" },
    { brand: "FORD", model: "MUSTANG" },
    { brand: "FORD", model: "MUSTANG" },
    { brand: "FORD", model: "MUSTANG" },
    { brand: "FORD", model: "MUSTANG" },
    { brand: "FORD", model: "MUSTANG" },
    { brand: "FORD", model: "	MSTANG GT" },
    { brand: "FORD", model: "	MSTANG GT" },
    { brand: "FORD", model: "PROBE" },
    { brand: "FORD", model: "RANGER " },
    { brand: "FORD", model: "RANGER" },
    { brand: "FORD", model: "RANGER" },
    { brand: "FORD", model: "RANGER" },
    { brand: "FORD", model: "RANGER" },
    { brand: "FORD", model: "RANGER" },
    { brand: "FORD", model: "RANGER" },
    { brand: "FORD", model: "RANGER" },
    { brand: "FORD", model: "RANGER" },
    { brand: "FORD", model: "RANGER" },
    { brand: "FORD", model: "	SERRA 280" },
    { brand: "FORD", model: "	SIERRA 30: /XR4i" },
    { brand: "FORD", model: "TAURUS" },
    { brand: "FORD", model: "TAURUS" },
    { brand: "FORD", model: "TAURUS" },
    { brand: "FORD", model: "TAURUS" },
    { brand: "FORD", model: "TAURUS" },
    { brand: "FORD", model: "TERRITORY" },
    { brand: "FORD", model: "THUNDERBIRD" },
    { brand: "FORD", model: "TRACER" },
    { brand: "FORD", model: "WINDSTAR" },
    { brand: "FORD", model: "ZEPHYR" },
    { brand: "GEELY", model: "CK" },
    { brand: "GEELY", model: "CK" },
    { brand: "GEELY", model: "HA" },
    { brand: "GEELY", model: "MK" },
    { brand: "GREAT", model: "WLL	DEER" },
    { brand: "GREAT", model: "WAL:	HVER CUV" },
    { brand: "GREAT", model: "WLL	SAFE" },
    { brand: "GREAT", model: "WLL	SAILOR" },
    { brand: "HAIMA", model: "7" },
    { brand: "HONDA", model: "ACCORD" },
    { brand: "HONDA", model: "ACCORD" },
    { brand: "HONDA", model: "ACCORD" },
    { brand: "HONDA", model: "ACCORD" },
    { brand: "HONDA", model: "ACCORD" },
    { brand: "HONDA", model: "ACCORD" },
    { brand: "HONDA", model: "ACCORD" },
    { brand: "HONDA", model: "CIVIC" },
    { brand: "HONDA", model: "CIVIC" },
    { brand: "HONDA", model: "	CVIC Si" },
    { brand: "HONDA", model: "CIVIC" },
    { brand: "HONDA", model: "CIVIC" },
    { brand: "HONDA", model: "CIVIC" },
    { brand: "HONDA", model: "	CVIC Si" },
    { brand: "HONDA", model: "CIVIC" },
    { brand: "HONDA", model: "	:R-" },
    { brand: "HONDA", model: "	:R-" },
    { brand: "HONDA", model: "	:R-" },
    { brand: "HONDA", model: "FIT" },
    { brand: "HONDA", model: "FIT" },
    { brand: "HONDA", model: "FIT" },
    { brand: "HONDA", model: "INTEGRA" },
    { brand: "HONDA", model: "LEGEND" },
    { brand: "HONDA", model: "LEGEND" },
    { brand: "HONDA", model: "LEGEND" },
    { brand: "HONDA", model: "ODYSSEY" },
    { brand: "HONDA", model: "ODYSSEY" },
    { brand: "HONDA", model: "ODYSSEY" },
    { brand: "HONDA", model: "PILOT" },
    { brand: "HONDA", model: "PRELUDE" },
    { brand: "HUMMER", model: "H2" },
    { brand: "HUMMER", model: "H2" },
    { brand: "HUMMER", model: "H3" },
    { brand: "HYUNDAI", model: "ACCENT" },
    { brand: "HYUNDAI", model: "ACCENT" },
    { brand: "HYUNDAI", model: "ACCENT" },
    { brand: "HYUNDAI", model: "ACCENT" },
    { brand: "HYUNDAI", model: "	AOS GLS" },
    { brand: "HYUNDAI", model: "AZERA" },
    { brand: "HYUNDAI", model: "	CUPE TIBURON" },
    { brand: "HYUNDAI", model: "	CUPE TIBURON" },
    { brand: "HYUNDAI", model: "	CUPE TIBURON" },
    { brand: "HYUNDAI", model: "ELANTRA" },
    { brand: "HYUNDAI", model: "ELANTRA" },
    { brand: "HYUNDAI", model: "ELANTRA" },
    { brand: "HYUNDAI", model: "ELANTRA" },
    { brand: "HYUNDAI", model: "EXCEL" },
    { brand: "HYUNDAI", model: "GALLOPER" },
    { brand: "HYUNDAI", model: "GETZ" },
    { brand: "HYUNDAI", model: "GETZ" },
    { brand: "HYUNDAI", model: "H1" },
    { brand: "HYUNDAI", model: "MATRIX" },
    { brand: "HYUNDAI", model: "	SNTA FE" },
    { brand: "HYUNDAI", model: "	SNTA FE" },
    { brand: "HYUNDAI", model: "	SOUPE LS" },
    { brand: "HYUNDAI", model: "SONATA" },
    { brand: "HYUNDAI", model: "SONATA" },
    { brand: "HYUNDAI", model: "SONATA" },
    { brand: "HYUNDAI", model: "SONATA" },
    { brand: "HYUNDAI", model: "SONATA" },
    { brand: "HYUNDAI", model: "SONATA" },
    { brand: "HYUNDAI", model: "SONATA" },
    { brand: "HYUNDAI", model: "TUCSON" },
    { brand: "HYUNDAI", model: "TUCSON" },
    { brand: "HYUNDAI", model: "TUCSON" },
    { brand: "HYUNDAI", model: "VERACRUZ" },
    { brand: "HYUNDAI", model: "VERNA" },
    { brand: "ISUZU", model: "AMIGO" },
    { brand: "ISUZU", model: "AMIGO" },
    { brand: "ISUZU", model: "AMIGO" },
    { brand: "ISUZU", model: "	CRIBE 442" },
    { brand: "ISUZU", model: "	CRIBE 442" },
    { brand: "ISUZU", model: "	CRIBE 442" },
    { brand: "ISUZU", model: "RODEO" },
    { brand: "ISUZU", model: "RODEO" },
    { brand: "ISUZU", model: "STYLUS" },
    { brand: "ISUZU", model: "TROOPER" },
    { brand: "ISUZU", model: "TROOPER" },
    { brand: "JAC", model: "J7" },
    { brand: "JAC", model: "	J2 ARENA" },
    { brand: "JAC", model: "	J4 NEVADO" },
    { brand: "JAC", model: "	J6 TEPUY" },
    { brand: "JAC", model: "	J8 SAVANNA" },
    { brand: "JAC", model: "	T: PCK UP" },
    { brand: "JAC", model: "	T6 PIC: U DI" },
    { brand: "JAC", model: "	T: PCK UP" },
    { brand: "JEEP", model: "	CEROKEE XJ" },
    { brand: "JEEP", model: "	CEROKEE XJ" },
    { brand: "JEEP", model: "	CHEROKE: LBERTY KJ" },
    { brand: "JEEP", model: "	CHEROKE: LBERTY KK" },
    { brand: "JEEP", model: "	CJ:5/" },
    { brand: "JEEP", model: "	:J-" },
    { brand: "JEEP", model: "COMANCHE" },
    { brand: "JEEP", model: "COMANCHE" },
    { brand: "JEEP", model: "COMMANDER" },
    { brand: "JEEP", model: "COMPASS" },
    { brand: "JEEP", model: "	GRAN: CEROKEE ZJ" },
    { brand: "JEEP", model: "	GRAN: CEROKEE WJ" },
    { brand: "JEEP", model: "	GRAN: CEROKEE WK" },
    { brand: "JEEP", model: "	GRAN: CEROKEE WK" },
    { brand: "JEEP", model: "	GRAN: CEROKEE WK2" },
    { brand: "JEEP", model: "	GRAN: CEROKEE WL" },
    { brand: "JEEP", model: "WAGONEER" },
    { brand: "JEEP", model: "WAGONEER" },
    { brand: "JEEP", model: "WAGONEER" },
    { brand: "JEEP", model: "	WANGLER YJ" },
    { brand: "JEEP", model: "	WANGLER YJ" },
    { brand: "JEEP", model: "	WANGLER YJ" },
    { brand: "JEEP", model: "WRANGLER" },
    { brand: "JEEP", model: "WRANGLER" },
    { brand: "JEEP", model: "WRANGLER" },
    { brand: "JEEP", model: "	WRANGLE: /RUBICON" },
    { brand: "JEEP", model: "	WRANGLE: /RUBICON" },
    { brand: "JMC", model: "	GAND AVENUE" },
    { brand: "JMC", model: "	JM REMAX" },
    { brand: "JMC", model: "	NE: VGUS FI" },
    { brand: "JMC", model: "	VIGU: PO FI" },
    { brand: "KIA", model: "CARENS" },
    { brand: "KIA", model: "CARENS" },
    { brand: "KIA", model: "CARENS" },
    { brand: "KIA", model: "CARNIVAL" },
    { brand: "KIA", model: "CERATO" },
    { brand: "KIA", model: "CERATO" },
    { brand: "KIA", model: "OPIRUS" },
    { brand: "KIA", model: "OPTIMA" },
    { brand: "KIA", model: "OPTIMA" },
    { brand: "KIA", model: "OPTIMA" },
    { brand: "KIA", model: "OPTIMA" },
    { brand: "KIA", model: "PICANTO" },
    { brand: "KIA", model: "RIO" },
    { brand: "KIA", model: "RIO" },
    { brand: "KIA", model: "RIO" },
    { brand: "KIA", model: "	RO STYLUS" },
    { brand: "KIA", model: "SEDONA" },
    { brand: "KIA", model: "SEDONA" },
    { brand: "KIA", model: "SEDONA" },
    { brand: "KIA", model: "SEPHIA" },
    { brand: "KIA", model: "SHUMA" },
    { brand: "KIA", model: "SORENTO" },
    { brand: "KIA", model: "SORENTO" },
    { brand: "KIA", model: "SPECTRA" },
    { brand: "KIA", model: "SPORTAGE" },
    { brand: "KIA", model: "SPORTAGE" },
    { brand: "KIA", model: "SPORTAGE" },
    { brand: "LADA", model: "MATRIUSHKA" },
    { brand: "LADA", model: "NIVA" },
    { brand: "LADA", model: "SAMARA" },
    { brand: "LADA", model: "SAMARA" },
    { brand: "LAND", model: "RVER	DEFENDER" },
    { brand: "LAND", model: "RVER	DISCOVERY" },
    { brand: "LAND", model: "RVER	DISCOVERY" },
    { brand: "LAND", model: "RVER	FREELANDER" },
    { brand: "LAND", model: "RVER	FREELANDER" },
    { brand: "LAND", model: "ROVE:	RNGE ROVER" },
    { brand: "LAND", model: "ROVE:	RNGE ROVER" },
    { brand: "LAND", model: "ROVE:	RNGE ROVER" },
    { brand: "LAND", model: "ROVE:	RNGE ROVER" },
    { brand: "LAND", model: "ROVE:	RNGE ROVER" },
    { brand: "LEXUS", model: "ES300" },
    { brand: "LEXUS", model: "GS350" },
    { brand: "LEXUS", model: "GX460" },
    { brand: "LEXUS", model: "GX470" },
    { brand: "LEXUS", model: "IS250" },
    { brand: "LEXUS", model: "IS300" },
    { brand: "LEXUS", model: "IS350" },
    { brand: "LEXUS", model: "LS400" },
    { brand: "LEXUS", model: "LS430" },
    { brand: "LEXUS", model: "LX470" },
    { brand: "LEXUS", model: "LX570" },
    { brand: "LEXUS", model: "LX600" },
    { brand: "LEXUS", model: "RX300" },
    { brand: "LEXUS", model: "RX350" },
    { brand: "LEXUS", model: "RX350" },
    { brand: "LEXUS", model: "SC300" },
    { brand: "LEXUS", model: "SC400" },
    { brand: "LEXUS", model: "SC430" },
    { brand: "MAZDA", model: "2" },
    { brand: "MAZDA", model: "3" },
    { brand: "MAZDA", model: "3" },
    { brand: "MAZDA", model: "3" },
    { brand: "MAZDA", model: "5" },
    { brand: "MAZDA", model: "6" },
    { brand: "MAZDA", model: "323" },
    { brand: "MAZDA", model: "323" },
    { brand: "MAZDA", model: "323" },
    { brand: "MAZDA", model: "626" },
    { brand: "MAZDA", model: "626" },
    { brand: "MAZDA", model: "ALLEGRO" },
    { brand: "MAZDA", model: "ALLEGRO" },
    { brand: "MAZDA", model: ":B-200" },
    { brand: "MAZDA", model: ":B-300" },
    { brand: "MAZDA", model: ":B-500" },
    { brand: "MAZDA", model: ":B-600" },
    { brand: "MAZDA", model: ":B-000" },
    { brand: "MAZDA", model: ":B-000" },
    { brand: "MAZDA", model: "	:T-0" },
    { brand: "MAZDA", model: "	:X-" },
    { brand: "MAZDA", model: "	:X-" },
    { brand: "MAZDA", model: "DEMIO" },
    { brand: "MAZDA", model: "MIATA" },
    { brand: "MAZDA", model: "MPV" },
    { brand: "MAZDA", model: "MPV" },
    { brand: "MAZDA", model: "	:X-" },
    { brand: "MAZDA", model: "	:X-" },
    { brand: "MAZDA", model: "	:X-" },
    { brand: "MAZDA", model: "	POTEGE LX" },
    { brand: "MERCEDES BENZ", model: "190" },
    { brand: "MERCEDES BENZ", model: "190" },
    { brand: "MERCEDES BENZ", model: "220B" },
    { brand: "MERCEDES BENZ", model: "220 :E/EB" },
    { brand: "MERCEDES BENZ", model: "230S" },
    { brand: "MERCEDES BENZ", model: "230SL" },
    { brand: "MERCEDES BENZ", model: "250 SE/S:C/L" },
    { brand: "MERCEDES BENZ", model: "250" },
    { brand: "MERCEDES BENZ", model: "280SE" },
    { brand: "MERCEDES BENZ", model: "300 E/S:L/L" },
    { brand: "MERCEDES BENZ", model: "300" },
    { brand: "MERCEDES BENZ", model: "C230K" },
    { brand: "MERCEDES BENZ", model: "C240" },
    { brand: "MERCEDES BENZ", model: "C280" },
    { brand: "MERCEDES BENZ", model: "C280" },
    { brand: "MERCEDES BENZ", model: "C320" },
    { brand: "MERCEDES BENZ", model: "CLK320" },
    { brand: "MERCEDES BENZ", model: "CLK430" },
    { brand: "MERCEDES BENZ", model: "CLK55" },
    { brand: "MERCEDES BENZ", model: "E220" },
    { brand: "MERCEDES BENZ", model: "E320" },
    { brand: "MERCEDES BENZ", model: "E320" },
    { brand: "MERCEDES BENZ", model: "E430" },
    { brand: "MERCEDES BENZ", model: "E350" },
    { brand: "MERCEDES BENZ", model: "E55" },
    { brand: "MERCEDES BENZ", model: "G500" },
    { brand: "MERCEDES BENZ", model: "ML230" },
    { brand: "MERCEDES BENZ", model: "ML320" },
    { brand: "MERCEDES BENZ", model: "ML350" },
    { brand: "MERCEDES BENZ", model: "ML430" },
    { brand: "MERCEDES BENZ", model: "ML500" },
    { brand: "MERCEDES BENZ", model: "S280" },
    { brand: "MERCEDES BENZ", model: "S320" },
    { brand: "MINI", model: "	MINI CORD  " },
    { brand: "MITSUBISHI", model: "	300 GT" },
    { brand: "MITSUBISHI", model: "DIAMANTE" },
    { brand: "MITSUBISHI", model: "DIAMANTE" },
    { brand: "MITSUBISHI", model: "ECLIPSE" },
    { brand: "MITSUBISHI", model: "ECLIPSE" },
    { brand: "MITSUBISHI", model: "ECLIPSE" },
    { brand: "MITSUBISHI", model: "ECLIPSE" },
    { brand: "MITSUBISHI", model: "ECLIPSE" },
    { brand: "MITSUBISHI", model: "	EPO VAN" },
    { brand: "MITSUBISHI", model: "	EPO VAN" },
    { brand: "MITSUBISHI", model: "GALANT" },
    { brand: "MITSUBISHI", model: "GALANT" },
    { brand: "MITSUBISHI", model: "GRANDIS" },
    { brand: "MITSUBISHI", model: "	L-20: PCK UP" },
    { brand: "MITSUBISHI", model: "	L-20: PCK UP" },
    { brand: "MITSUBISHI", model: "LANCER" },
    { brand: "MITSUBISHI", model: "LANCER" },
    { brand: "MITSUBISHI", model: "LANCER" },
    { brand: "MITSUBISHI", model: "LANCER" },
    { brand: "MITSUBISHI", model: "LANCER" },
    { brand: "MITSUBISHI", model: "LANCER" },
    { brand: "MITSUBISHI", model: "LANCER" },
    { brand: "MITSUBISHI", model: "LANCER" },
    { brand: "MITSUBISHI", model: "LANCER" },
    { brand: "MITSUBISHI", model: "MF" },
    { brand: "MITSUBISHI", model: "MF" },
    { brand: "MITSUBISHI", model: "MS" },
    { brand: "MITSUBISHI", model: "MX" },
    { brand: "MITSUBISHI", model: "MX" },
    { brand: "MITSUBISHI", model: "MIRAGE" },
    { brand: "MITSUBISHI", model: "	MNTERO DAKAR" },
    { brand: "MITSUBISHI", model: "	MNTERO LIMITED" },
    { brand: "MITSUBISHI", model: "	MNTERO LIMITED" },
    { brand: "MITSUBISHI", model: "	MNTERO LIMITED" },
    { brand: "MITSUBISHI", model: "	MNTERO LIMITED" },
    { brand: "MITSUBISHI", model: "	MNTERO SPORT" },
    { brand: "MITSUBISHI", model: "	MNTERO SPORT" },
    { brand: "MITSUBISHI", model: "OUTLANDER" },
    { brand: "MITSUBISHI", model: "OUTLANDER" },
    { brand: "MITSUBISHI", model: "	PANEL :L-00" },
    { brand: "MITSUBISHI", model: "	PANEL :L-00" },
    { brand: "MITSUBISHI", model: "	PANEL :L-00" },
    { brand: "MITSUBISHI", model: "SIGMA" },
    { brand: "MITSUBISHI", model: "SIGNO" },
    { brand: "MITSUBISHI", model: "	SACE WAGON" },
    { brand: "MITSUBISHI", model: "	SACE WAGON" },
    { brand: "MITSUBISHI", model: "	SAR WAGON" },
    { brand: "MITSUBISHI", model: "	WGON VAN" },
    { brand: "MITSUBISHI", model: "	WGON VAN" },
    { brand: "NISSAN", model: "240SX" },
    { brand: "NISSAN", model: "300ZX" },
    { brand: "NISSAN", model: "350Z" },
    { brand: "NISSAN", model: "ALTIMA" },
    { brand: "NISSAN", model: "ALTIMA" },
    { brand: "NISSAN", model: "ALTIMA" },
    { brand: "NISSAN", model: "MAXIMA" },
    { brand: "NISSAN", model: "MURANO" },
    { brand: "NISSAN", model: "PATHFINDER" },
    { brand: "NISSAN", model: "PATHFINDER" },
    { brand: "NISSAN", model: "PATHFINDER" },
    { brand: "NISSAN", model: "	PATROL L/:L-0" },
    { brand: "NISSAN", model: "PATROL" },
    { brand: "NISSAN", model: "	PCK UP" },
    { brand: "NISSAN", model: "	PCK UP" },
    { brand: "NISSAN", model: "	PIC: U FRONTIER" },
    { brand: "NISSAN", model: "	PIC: U TITAN" },
    { brand: "NISSAN", model: "QUEST" },
    { brand: "NISSAN", model: "SENTRA" },
    { brand: "NISSAN", model: "SENTRA" },
    { brand: "NISSAN", model: "SENTRA" },
    { brand: "NISSAN", model: "SENTRA" },
    { brand: "NISSAN", model: "SENTRA" },
    { brand: "NISSAN", model: "SENTRA" },
    { brand: "NISSAN", model: "TERRANO" },
    { brand: "NISSAN", model: "TIIDA" },
    { brand: "NISSAN", model: "XTERRA" },
    { brand: "NISSAN", model: ":X-RAIL" },
    { brand: "NISSAN", model: ":X-RAIL" },
    { brand: "NISSAN", model: ":X-RAIL" },
    { brand: "PEUGEOT", model: "206CC" },
    { brand: "PEUGEOT", model: "206RC" },
    { brand: "PEUGEOT", model: "206XR" },
    { brand: "PEUGEOT", model: "206XR" },
    { brand: "PEUGEOT", model: "	207  Compac: Oe Line" },
    { brand: "PEUGEOT", model: "	207: Cmpact Sedan" },
    { brand: "PEUGEOT", model: "306" },
    { brand: "PEUGEOT", model: "307" },
    { brand: "PEUGEOT", model: "407" },
    { brand: "PEUGEOT", model: "407" },
    { brand: "PEUGEOT", model: "408" },
    { brand: "PEUGEOT", model: "607" },
    { brand: "PEUGEOT", model: "EXPERT" },
    { brand: "PEUGEOT", model: "PARTNER" },
    { brand: "RENAULT", model: "CLIO" },
    { brand: "RENAULT", model: "CLIO" },
    { brand: "RENAULT", model: "CLIO" },
    { brand: "RENAULT", model: "DUSTER" },
    { brand: "RENAULT", model: "FUEGO" },
    { brand: "RENAULT", model: "FUEGO" },
    { brand: "RENAULT", model: "GALA" },
    { brand: "RENAULT", model: "KANGOO" },
    { brand: "RENAULT", model: "	KNGOO SPORTWAY" },
    { brand: "RENAULT", model: "	KNGOO EXPRESS" },
    { brand: "RENAULT", model: "KOLEOS" },
    { brand: "RENAULT", model: "LAGUNA" },
    { brand: "RENAULT", model: "LOGAN" },
    { brand: "RENAULT", model: "LOGAN" },
    { brand: "RENAULT", model: "MEGANE" },
    { brand: "RENAULT", model: "MEGANE" },
    { brand: "RENAULT", model: "	MGANE II" },
    { brand: "RENAULT", model: ":R-1" },
    { brand: "RENAULT", model: ":R-2" },
    { brand: "RENAULT", model: ":R-6" },
    { brand: "RENAULT", model: ":R-8" },
    { brand: "RENAULT", model: ":R-8" },
    { brand: "RENAULT", model: ":R-9" },
    { brand: "RENAULT", model: ":R-9" },
    { brand: "RENAULT", model: ":R-9" },
    { brand: "RENAULT", model: ":R-1" },
    { brand: "RENAULT", model: ":R-0" },
    { brand: "RENAULT", model: ":R-" },
    { brand: "RENAULT", model: ":R-" },
    { brand: "RENAULT", model: "SANDERO" },
    { brand: "RENAULT", model: "SANDERO" },
    { brand: "RENAULT", model: "SCENIC" },
    { brand: "RENAULT", model: "SCENIC" },
    { brand: "RENAULT", model: "SCENIC" },
    { brand: "RENAULT", model: "STEPWAY" },
    { brand: "RENAULT", model: "SYMBOL" },
    { brand: "RENAULT", model: "SYMBOL" },
    { brand: "RENAULT", model: "SYMBOL" },
    { brand: "RENAULT", model: "TWINGO" },
    { brand: "RENAULT", model: "TWINGO" },
    { brand: "RENAULT", model: "TWINGO" },
    { brand: "SEAT", model: "ALHAMBRA" },
    { brand: "SEAT", model: "ALTEA" },
    { brand: "SEAT", model: "CORDOBA" },
    { brand: "SEAT", model: "CORDOBA" },
    { brand: "SEAT", model: "CORDOBA" },
    { brand: "SEAT", model: "IBIZA" },
    { brand: "SEAT", model: "IBIZA" },
    { brand: "SEAT", model: "IBIZA" },
    { brand: "SEAT", model: "IBIZA" },
    { brand: "SEAT", model: "IBIZA" },
    { brand: "SEAT", model: "LEON" },
    { brand: "SEAT", model: "	LON FR" },
    { brand: "SEAT", model: "	LON FR" },
    { brand: "SEAT", model: "	LEO: RCUPRA" },
    { brand: "SEAT", model: "TOLEDO" },
    { brand: "SEAT", model: "TOLEDO" },
    { brand: "SEAT", model: "TOLEDO" },
    { brand: "SKODA", model: "FABIA" },
    { brand: "SKODA", model: "OCTAVIA" },
    { brand: "SKODA", model: "OCTAVIA" },
    { brand: "SUBARU", model: "FORESTER" },
    { brand: "SUBARU", model: "FORESTER" },
    { brand: "SUBARU", model: "IMPREZA" },
    { brand: "SUBARU", model: "IMPREZA" },
    { brand: "SUBARU", model: "IMPREZA" },
    { brand: "SUBARU", model: "	IPREZA RS" },
    { brand: "SUBARU", model: "	IPREZA WRX" },
    { brand: "SUBARU", model: "	IMPREZ: WX STI" },
    { brand: "SUBARU", model: "	JSTY GL" },
    { brand: "SUBARU", model: "LEGACY" },
    { brand: "SUBARU", model: "LEGACY" },
    { brand: "SUBARU", model: "LEGACY" },
    { brand: "SUBARU", model: "LEGACY" },
    { brand: "SUBARU", model: "LEGACY" },
    { brand: "SUBARU", model: "OUTBACK" },
    { brand: "SUBARU", model: "OUTBACK" },
    { brand: "SUBARU", model: "SVX" },
    { brand: "SUBARU", model: "	TIBECA B9" },
    { brand: "SUZUKI", model: "JIMNY" },
    { brand: "SUZUKI", model: "CELERIO" },
    { brand: "SUZUKI", model: "	GAND VITARA" },
    { brand: "SUZUKI", model: "SAMURAI" },
    { brand: "SUZUKI", model: "	SDEKICK JX" },
    { brand: "TATA", model: "INDICA" },
    { brand: "TATA", model: "INDIGO" },
    { brand: "TATA", model: "	IDIGO SW" },
    { brand: "TATA", model: "SAFARI" },
    { brand: "TOYOTA", model: "	4RUNNER" },
    { brand: "TOYOTA", model: "	4RUNNER" },
    { brand: "TOYOTA", model: "	4RUNNER" },
    { brand: "TOYOTA", model: "	4RUNNER" },
    { brand: "TOYOTA", model: "	4RUNNER" },
    { brand: "TOYOTA", model: "AVALON" },
    { brand: "TOYOTA", model: "CAMRY" },
    { brand: "TOYOTA", model: "CAMRY" },
    { brand: "TOYOTA", model: "CAMRY" },
    { brand: "TOYOTA", model: "CAMRY" },
    { brand: "TOYOTA", model: "CAMRY" },
    { brand: "TOYOTA", model: "CAMRY" },
    { brand: "TOYOTA", model: "CAMRY" },
    { brand: "TOYOTA", model: "CELICA" },
    { brand: "TOYOTA", model: "CELICA" },
    { brand: "TOYOTA", model: "CELICA" },
    { brand: "TOYOTA", model: "CELICA" },
    { brand: "TOYOTA", model: "CELICA" },
    { brand: "TOYOTA", model: "CELICA" },
    { brand: "TOYOTA", model: ":C-R" },
    { brand: "TOYOTA", model: "COROLLA" },
    { brand: "TOYOTA", model: "COROLLA" },
    { brand: "TOYOTA", model: "COROLLA" },
    { brand: "TOYOTA", model: "COROLLA" },
    { brand: "TOYOTA", model: "COROLLA" },
    { brand: "TOYOTA", model: "COROLLA" },
    { brand: "TOYOTA", model: "COROLLA" },
    { brand: "TOYOTA", model: "	CROLLA IMP." },
    { brand: "TOYOTA", model: "COROLLA" },
    { brand: "TOYOTA", model: "	CROLLA CROSS" },
    { brand: "TOYOTA", model: "FJ40" },
    { brand: "TOYOTA", model: "	FJ4: PCK UP" },
    { brand: "TOYOTA", model: "	F55 SAMURAI" },
    { brand: "TOYOTA", model: "	F60 SAMURAI" },
    { brand: "TOYOTA", model: "	F62 SAMURAI" },
    { brand: "TOYOTA", model: "	F70 Macho" },
    { brand: "TOYOTA", model: "	F70 Macho" },
    { brand: "TOYOTA", model: "	F70 Macho" },
    { brand: "TOYOTA", model: "	F70 Macho" },
    { brand: "TOYOTA", model: "	FJ71 Macho" },
    { brand: "TOYOTA", model: "	FJ7: PCK UP" },
    { brand: "TOYOTA", model: "	FJ76 Macho" },
    { brand: "TOYOTA", model: "	FZJ7: PCK UP" },
    { brand: "TOYOTA", model: "	FZJ7: PCK UP" },
    { brand: "TOYOTA", model: "	F CRUISER" },
    { brand: "TOYOTA", model: "	F CRUISER" },
    { brand: "TOYOTA", model: "FORTUNER" },
    { brand: "TOYOTA", model: "HIACE" },
    { brand: "TOYOTA", model: "HILUX" },
    { brand: "TOYOTA", model: "HILUX" },
    { brand: "TOYOTA", model: "HILUX" },
    { brand: "TOYOTA", model: "HILUX" },
    { brand: "TOYOTA", model: "HILUX" },
    { brand: "TOYOTA", model: "HILUX" },
    { brand: "TOYOTA", model: "HILUX" },
    { brand: "TOYOTA", model: "HILUX" },
    { brand: "TOYOTA", model: "	LAN: CUISER  FJ55" },
    { brand: "TOYOTA", model: "	LAN: CUISER  FJ55" },
    { brand: "TOYOTA", model: "	LAND CRUISER 4500 V: /FJ80" },
    { brand: "TOYOTA", model: "	LAND CRUISER 4500 V: /FJ80" },
    { brand: "TOYOTA", model: "	LAN: CUISER 200" },
    { brand: "TOYOTA", model: "	LAN: CUISER 200" },
    { brand: "TOYOTA", model: "MERU" },
    { brand: "TOYOTA", model: "	M 2" },
    { brand: "TOYOTA", model: "PASEO" },
    { brand: "TOYOTA", model: "PRADO" },
    { brand: "TOYOTA", model: "PRADO" },
    { brand: "TOYOTA", model: "PREVIA" },
    { brand: "TOYOTA", model: "	RV 4" },
    { brand: "TOYOTA", model: "	RV 4" },
    { brand: "TOYOTA", model: "	RV 4" },
    { brand: "TOYOTA", model: "	RV 4" },
    { brand: "TOYOTA", model: "SEQUOIA" },
    { brand: "TOYOTA", model: "SEQUOIA" },
    { brand: "TOYOTA", model: "SEQUOIA" },
    { brand: "TOYOTA", model: "SEQUOIA" },
    { brand: "TOYOTA", model: "SIENNA" },
    { brand: "TOYOTA", model: "SIENNA" },
    { brand: "TOYOTA", model: "SIENNA" },
    { brand: "TOYOTA", model: "SKY" },
    { brand: "TOYOTA", model: "STARLET" },
    { brand: "TOYOTA", model: "TACOMA" },
    { brand: "TOYOTA", model: "TACOMA" },
    { brand: "TOYOTA", model: "TERCEL" },
    { brand: "TOYOTA", model: "TERIOS" },
    { brand: "TOYOTA", model: "	TERIOS  :E-O" },
    { brand: "TOYOTA", model: "TUNDRA" },
    { brand: "TOYOTA", model: "TUNDRA" },
    { brand: "TOYOTA", model: "TUNDRA" },
    { brand: "TOYOTA", model: "TUNDRA" },
    { brand: "TOYOTA", model: "TUNDRA" },
    { brand: "TOYOTA", model: "YARIS" },
    { brand: "TOYOTA", model: "YARIS" },
    { brand: "TOYOTA", model: "	YRIS BELTA" },
    { brand: "TOYOTA", model: "YARIS" },
    { brand: "TOYOTA", model: "	YRIS CROSS" },
    { brand: "VENIRAUTO", model: "CENTAURO" },
    { brand: "VENIRAUTO", model: "CENTAURO" },
    { brand: "VENIRAUTO", model: "TURPIAL" },
    { brand: "VOLKSWAGEN", model: "BORA" },
    { brand: "VOLKSWAGEN", model: "BORA" },
    { brand: "VOLKSWAGEN", model: "BRASILIA" },
    { brand: "VOLKSWAGEN", model: "CORRADO" },
    { brand: "VOLKSWAGEN", model: "CROSSFOX" },
    { brand: "VOLKSWAGEN", model: "ESCARABAJO" },
    { brand: "VOLKSWAGEN", model: "ESCARABAJO" },
    { brand: "VOLKSWAGEN", model: "ESCARABAJO" },
    { brand: "VOLKSWAGEN", model: "FOX" },
    { brand: "VOLKSWAGEN", model: "GOL" },
    { brand: "VOLKSWAGEN", model: "GOL" },
    { brand: "VOLKSWAGEN", model: "GOLF" },
    { brand: "VOLKSWAGEN", model: "GOLF" },
    { brand: "VOLKSWAGEN", model: "GOLF" },
    { brand: "VOLKSWAGEN", model: "GOLF" },
    { brand: "VOLKSWAGEN", model: "GOLF" },
    { brand: "VOLKSWAGEN", model: "GOLF" },
    { brand: "VOLKSWAGEN", model: "JETTA" },
    { brand: "VOLKSWAGEN", model: "JETTA" },
    { brand: "VOLKSWAGEN", model: "JETTA" },
    { brand: "VOLKSWAGEN", model: "JETTA" },
    { brand: "VOLKSWAGEN", model: "JETTA" },
    { brand: "VOLKSWAGEN", model: "KOMBI" },
    { brand: "VOLKSWAGEN", model: "KOMBI" },
    { brand: "VOLKSWAGEN", model: "	NW BEETLE" },
    { brand: "VOLKSWAGEN", model: "	NW BEETLE" },
    { brand: "VOLKSWAGEN", model: "PARATI" },
    { brand: "VOLKSWAGEN", model: "PASSAT" },
    { brand: "VOLKSWAGEN", model: "PASSAT" },
    { brand: "VOLKSWAGEN", model: "PASSAT" },
    { brand: "VOLKSWAGEN", model: "PASSAT" },
    { brand: "VOLKSWAGEN", model: "POLO" },
    { brand: "VOLKSWAGEN", model: "POLO" },
    { brand: "VOLKSWAGEN", model: "POLO" },
    { brand: "VOLKSWAGEN", model: "SANTANA" },
    { brand: "VOLKSWAGEN", model: "SAVEIRO" },
    { brand: "VOLKSWAGEN", model: "	SACE FOX" },
    { brand: "VOLKSWAGEN", model: "VENTO" },
    { brand: "VOLKSWAGEN", model: "VENTO" },
    { brand: "VOLVO", model: "740" },
    { brand: "VOLVO", model: "850" },
    { brand: "VOLVO", model: "940" },
    { brand: "VOLVO", model: "960" },
];
