//DIAMETRO EXTERNO
export const validCategoriesOD = [
    "Filtro Aceite Spin On",
    "Filtro Aceite Elemento",
    "Filtro Aceite Centrifugo",
    "Filtro Aire Cilíndrico",
    "Filtro Combustible In-Line / In-Tank / Regulador / Modulo",
    "Filtro Combustible Spin On",
    "Filtro Combustible Cartucho / CAV",
    "Filtro Secante Spin On",
    "Filtro Hidraúlico Spin On",
    "Filtro Hidraúlico Elemento",
    "Filtro Refrigerante Spin On",
    "Filtro Hidraúlico Vaso",
];

// export const validCategoriesOD2 = [
//     "Filtro Aceite Spin On",
//     "Filtro Aceite Elemento",
//     "Filtro Aceite Centrifugo",
//     "Filtro Aire Cilíndrico",
//     "Filtro Combustible In-Line / In-Tank / Regulador / Modulo",
//     "Filtro Combustible Spin On",
//     "Filtro Combustible Cartucho / CAV",
//     "Filtro Secante Spin On",
//     "Filtro Hidraúlico Spin On",
//     "Filtro Hidraúlico Elemento",
//     "Filtro Refrigerante Spin On",
// ];

export const validCategoriesTH = [
    "Filtro Aceite Spin On",
    "Filtro Combustible Spin On",
    "Filtro Secante Spin On",
    "Filtro Hidraúlico Spin On",
    "Filtro Refrigerante Spin On",
];

export const validCategoriesGSOD = ["Filtro Aceite Spin On"];
export const validCategoryGSID = ["Filtro Aceite Spin On"];
export const validCategoryByPassValve = ["Filtro Aceite Spin On"];
export const validCategoryAntiDrain = ["Filtro Aceite Spin On"];
export const validCategoriesDiametroInterno = [
    "Filtro Aceite Elemento",
    "Filtro Aire Cilíndrico",
    "Filtro Combustible Cartucho / CAV",
    "Filtro Hidraúlico Elemento",
];

export const validCategoriesDiametroInterno2 = [
    "Filtro Aceite Elemento",
    "Filtro Aire Cilíndrico",
    "Filtro Combustible Cartucho / CAV",
];
export const validCategoriesEntrada = [
    "Filtro Aceite Centrífugo",
    "Filtro Combustible In-Line / In-Tank / Regulador / Modulo",
];
export const validCategoriesSalida = [
    "Filtro Aceite Centrífugo",
    "Filtro Combustible In-Line / In-Tank / Regulador / Modulo",
];

export const validCategoriesDiametroExterno = [
    "Filro Aceite Spin On",
    "Filtro Aceite Elemento",
    "Filtro Aceite Centrifugo",
    "Filtro Aire Cilíndrico",
    "Filtro Refrigerante Spin On",
    "Filtro Aire Toroide Rect. o Elip",
];
export const validCategoriesDiametroRosca = [
    "Filtro Refrigerante Spin On",
    "Filtro Hidraúlico Spin On",
    "Filtro Hidraúlico Spin",
    "Filtro Secante Spin On",
    "Filtro Combustible Spin On",
];

export const validCategoriesLonguitud = [
    "Filtro Aire Panel",
    "Filtro Aire Toroide Rect. o Elip.",
    "Filtro Cabina Panel",
    "Filtro Hidraúlico Vaso",
];

export const validCategoriesW = [
    "Filtro Aire Panel",
    "Filtro Cabina Panel",
    "Filtro Hidraúlico Vaso",
];

export const validCategoriesWe = ["Filtro Aire Toroide Rect. o Elip."];

export const validCategoriesWi = ["Filtro Aire Toroide Rect. o Elip."];

export const validCategoryDrain = [
    "Filtro Combustible In-Line / In-Tank / Regulador / Modulo",
    "Filtro Combustible Spin On",
];

export const validCategoryLe = ["Filtro Aire Toroide Rect. o Elip."];

export const validCategoryLi = ["Filtro Aire Toroide Rect. o Elip."];

export const brands = [
    "ACURA",
    "AGRALE",
    "ALFA ROMEO",
    "ALLIS-CHALMERS",
    "AMC",
    "ARO",
    "ASIA",
    "ASTRA",
    "AUDI",
    "AUTOGAGO",
    "BELARUS",
    "BMW",
    "BOBCAT",
    "BOMAG",
    "CASE",
    "CATERPILLAR",
    "CHANGAN",
    "CHERY",
    "CHEVROLET",
    "CHRYSLER",
    "CINASCAR",
    "CITROEN",
    "DACIA",
    "DAEWOO",
    "DAIHATSU",
    "DODGE",
    "DONGFENG",
    "EBRO",
    "ENCAVA",
    "FIAT",
    "FIATAGRI",
    "FORD",
    "FOTON",
    "FREIGHTLINER",
    "GEELY",
    "GREAT WALL",
    "GURI",
    "HAIMA",
    "HINO",
    "HITACHI",
    "HONDA",
    "HUMMER",
    "HYUNDAI",
    "IHC HARVESTER",
    "INTERNATIONAL",
    "ISUZU",
    "IVECO",
    "JAC",
    "JEEP",
    "JMC",
    "JOHN DEERE",
    "KAMAZ",
    "KENWORTH DE LA MONTAÑA",
    "KIA",
    "KOBELCO",
    "KOMATSU",
    "LADA",
    "LAND ROVER",
    "LEXUS",
    "LIEBHERR",
    "MACK",
    "MASSEY FERGUSON",
    "MAXUS",
    "MAZ",
    "MAZDA",
    "MERCEDES BENZ",
    "MINI",
    "MITSUBISHI",
    "NEW HOLLAND",
    "NISSAN",
    "PEGASO",
    "PEUGEOT",
    "RENAULT",
    "SCANIA",
    "SEAT",
    "SINOTRUCK",
    "SKODA",
    "SUBARU",
    "SUZUKI",
    "TATA",
    "TOYOTA",
    "TRACTOVEN",
    "VALTRA",
    "VENIRAUTO",
    "VOLKSWAGEN",
    "VOLVO",
    "YUTONG",
];

export const modelList = [
    { brand: "ACURA", model: "INTEGRA" },
    { brand: "ACURA", model: "VIGOR" },
    { brand: "AGRALE", model: "VOLARE A5" },
    { brand: "AGRALE", model: "VOLARE W9" },
    { brand: "ALFA ROMEO", model: "146 Ti" },
    { brand: "ALFA ROMEO", model: "156T" },
    { brand: "ALLIS-CHALMERS", model: "TRACTOR 7050" },
    { brand: "ALLIS-CHALMERS", model: "TRACTOR 7060" },
    { brand: "ALLIS-CHALMERS", model: "TRACTOR ORUGA  7G-B" },
    { brand: "ALLIS-CHALMERS", model: "TRACTOR ORUGA  HD-6" },
    { brand: "AMC", model: "HORNET" },
    { brand: "AMC", model: "JAVELIN" },
    { brand: "ARO", model: "BUFFALO" },
    { brand: "ARO", model: "DAKTARI" },
    { brand: "ARO", model: "RANGER" },
    { brand: "ARO", model: "RINO PICK-UP" },
    { brand: "ASIA", model: "TOWNER" },
    { brand: "ASTRA", model: "HD8" },
    { brand: "AUDI", model: "90" },
    { brand: "AUDI", model: "100" },
    { brand: "AUDI", model: "A3" },
    { brand: "AUDI", model: "A4" },
    { brand: "AUDI", model: "A6 " },
    { brand: "AUDI", model: "A6  " },
    { brand: "AUDI", model: "RS4" },
    { brand: "AUDI", model: "RS6" },
    { brand: "AUDI", model: "S4" },
    { brand: "AUDI", model: "S6" },
    { brand: "AUDI", model: "TT" },
    { brand: "AUTOGAGO", model: "A475 U HINO" },
    { brand: "BELARUS", model: "TRACTOR 1025" },
    { brand: "BELARUS", model: "TRACTOR 1221.4" },
    { brand: "BMW", model: "318i" },
    { brand: "BMW", model: "320i" },
    { brand: "BMW", model: "323i" },
    { brand: "BMW", model: "325i" },
    { brand: "BMW", model: "328i" },
    { brand: "BMW", model: "525i" },
    { brand: "BMW", model: "528i" },
    { brand: "BMW", model: "530i" },
    { brand: "BMW", model: "735i" },
    { brand: "BMW", model: "X3" },
    { brand: "BOBCAT", model: "CARGADOR 763" },
    { brand: "BOBCAT", model: "CARGADOR T140" },
    { brand: "BOBCAT", model: "EXCAVADORA 325" },
    { brand: "BOBCAT", model: "EXCAVADORA 328" },
    { brand: "BOMAG", model: "RODILLO COMPACTADOR BW211" },
    { brand: "CASE", model: "CARGADOR 921C" },
    { brand: "CASE", model: "CARGADOR SR200" },
    { brand: "CASE", model: "RETRO EXCABADORA 580L" },
    { brand: "CASE", model: "RETRO EXCABADORA 590L" },
    { brand: "CASE", model: "RETRO EXCAVADORA 580M" },
    { brand: "CASE", model: "TRACTOR 2294" },
    { brand: "CASE", model: "TRACTOR 9270" },
    { brand: "CATERPILLAR", model: "518 SKIDDER" },
    { brand: "CATERPILLAR", model: "528 SKIDDER" },
    { brand: "CATERPILLAR", model: "CARGADOR 920" },
    { brand: "CATERPILLAR", model: "CARGADOR 928F" },
    { brand: "CATERPILLAR", model: "CARGADOR 936E" },
    { brand: "CATERPILLAR", model: "CARGADOR 950E" },
    { brand: "CATERPILLAR", model: "CARGADOR 966C" },
    { brand: "CATERPILLAR", model: "CARGADOR 980C" },
    { brand: "CATERPILLAR", model: "CARGADOR COMPACTO 216" },
    { brand: "CATERPILLAR", model: "CARGADOR COMPACTO 228" },
    { brand: "CATERPILLAR", model: "CARGADOR COMPACTO 242" },
    { brand: "CATERPILLAR", model: "COMPACTADOR  PR1000" },
    { brand: "CATERPILLAR", model: "COMPACTADOR 826G" },
    { brand: "CATERPILLAR", model: "COMPACTADOR CB434B" },
    { brand: "CATERPILLAR", model: "COMPACTADOR CB434C" },
    { brand: "CATERPILLAR", model: "EXCAVADORAS 311" },
    { brand: "CATERPILLAR", model: "EXCAVADORAS 320BL" },
    { brand: "CATERPILLAR", model: "EXCAVADORAS 320CL" },
    { brand: "CATERPILLAR", model: "EXCAVADORAS 320D / 320DL" },
    { brand: "CATERPILLAR", model: "EXCAVADORAS 322BL" },
    { brand: "CATERPILLAR", model: "EXCAVADORAS 324DL" },
    { brand: "CATERPILLAR", model: "EXCAVADORAS 325CL" },
    { brand: "CATERPILLAR", model: "EXCAVADORAS 325DL" },
    { brand: "CATERPILLAR", model: "EXCAVADORAS 330L" },
    { brand: "CATERPILLAR", model: "EXCAVADORAS E110B" },
    { brand: "CATERPILLAR", model: "GRADERS 120B" },
    { brand: "CATERPILLAR", model: "GRADERS 12E" },
    { brand: "CATERPILLAR", model: "GRADERS 12G" },
    { brand: "CATERPILLAR", model: "MONTACARGAS DP15" },
    { brand: "CATERPILLAR", model: "MONTACARGAS DP18" },
    { brand: "CATERPILLAR", model: "MONTACARGAS TH103" },
    { brand: "CATERPILLAR", model: "MONTACARGAS VC60D" },
    { brand: "CATERPILLAR", model: "PAYLOADER 966, 966A, 966B" },
    { brand: "CATERPILLAR", model: "RASPADOR 621B" },
    { brand: "CATERPILLAR", model: "RETRO EXCAVADORA 414E" },
    { brand: "CATERPILLAR", model: "RETRO EXCAVADORA 416B" },
    { brand: "CATERPILLAR", model: "RETRO EXCAVADORA 416C" },
    { brand: "CATERPILLAR", model: "RETRO EXCAVADORA 416D" },
    { brand: "CATERPILLAR", model: "RETRO EXCAVADORA 420D" },
    { brand: "CATERPILLAR", model: "RODILLO COMPACTADOR CP533E" },
    { brand: "CATERPILLAR", model: "TRACTOR ORUGA D3C" },
    { brand: "CATERPILLAR", model: "TRACTOR ORUGA D4B" },
    { brand: "CATERPILLAR", model: "TRACTOR ORUGA D4C" },
    { brand: "CATERPILLAR", model: "TRACTOR ORUGA D4D" },
    { brand: "CATERPILLAR", model: "TRACTOR ORUGA D4H" },
    { brand: "CATERPILLAR", model: "TRACTOR ORUGA D5C" },
    { brand: "CATERPILLAR", model: "TRACTOR ORUGA D5G" },
    { brand: "CATERPILLAR", model: "TRACTOR ORUGA D6C" },
    { brand: "CATERPILLAR", model: "TRACTOR ORUGA D6D, D6E" },
    { brand: "CATERPILLAR", model: "TRACTOR ORUGA D6R" },
    { brand: "CATERPILLAR", model: "TRACTOR ORUGA D9H" },
    { brand: "CATERPILLAR", model: "TRACTOR ORUGA D9L" },
    { brand: "CHANGAN", model: "ALSVIN SINC/AUTO" },
    { brand: "CHANGAN", model: "CS15" },
    { brand: "CHANGAN", model: "CS35 PLUS" },
    { brand: "CHANGAN", model: "KAICENE F70/ HUNTER" },
    { brand: "CHERY", model: "ARAUCA A1" },
    { brand: "CHERY", model: "ARAUCA S15" },
    { brand: "CHERY", model: "GRAND TIGER 4X2" },
    { brand: "CHERY", model: "GRAND TIGER 4X4" },
    { brand: "CHERY", model: "H5 VAN" },
    { brand: "CHERY", model: "ORINOCO" },
    { brand: "CHERY", model: "QQ" },
    { brand: "CHERY", model: "TIGGO" },
    { brand: "CHERY", model: "X1" },
    { brand: "CHEVROLET", model: "ASTRA CONFORT" },
    { brand: "CHEVROLET", model: "ASTRA COUPE" },
    { brand: "CHEVROLET", model: "ASTRA ELEGANCE" },
    { brand: "CHEVROLET", model: "ASTRA TURBO" },
    { brand: "CHEVROLET", model: "AVALANCHE" },
    { brand: "CHEVROLET", model: "AVEO" },
    { brand: "CHEVROLET", model: "AVEO LS" },
    { brand: "CHEVROLET", model: "AVEO LT" },
    { brand: "CHEVROLET", model: "BLAZER" },
    { brand: "CHEVROLET", model: "BRIGADIER" },
    { brand: "CHEVROLET", model: "C30" },
    { brand: "CHEVROLET", model: "C3500" },
    { brand: "CHEVROLET", model: "C3500 HD" },
    { brand: "CHEVROLET", model: "C60" },
    { brand: "CHEVROLET", model: "C70" },
    { brand: "CHEVROLET", model: "C70 KODIAK" },
    { brand: "CHEVROLET", model: "CAMARO 1st-Gen" },
    { brand: "CHEVROLET", model: "CAMARO 2nd-Gen" },
    { brand: "CHEVROLET", model: "CAMARO 3rd-Gen" },
    { brand: "CHEVROLET", model: "CAMARO 4th-Gen I" },
    { brand: "CHEVROLET", model: "CAMARO 4th-Gen II" },
    { brand: "CHEVROLET", model: "CAPRICE" },
    { brand: "CHEVROLET", model: "CAPTIVA" },
    { brand: "CHEVROLET", model: "CARGO VAN" },
    { brand: "CHEVROLET", model: "CAVALIER" },
    { brand: "CHEVROLET", model: "CAVALIER  Z24" },
    { brand: "CHEVROLET", model: "CELEBRITY" },
    { brand: "CHEVROLET", model: "CENTURY" },
    { brand: "CHEVROLET", model: "CHEVELLE" },
    { brand: "CHEVROLET", model: "CHEVETTE" },
    { brand: "CHEVROLET", model: "CHEVY  " },
    { brand: "CHEVROLET", model: "COLORADO" },
    { brand: "CHEVROLET", model: "COLORADO " },
    { brand: "CHEVROLET", model: "CORSA" },
    { brand: "CHEVROLET", model: "CORSA " },
    { brand: "CHEVROLET", model: "CORSICA" },
    { brand: "CHEVROLET", model: "CORVETTE" },
    { brand: "CHEVROLET", model: "CRUZE" },
    { brand: "CHEVROLET", model: "EPICA" },
    { brand: "CHEVROLET", model: "ESTEEM" },
    { brand: "CHEVROLET", model: "EXPRESS CARGO 1500" },
    { brand: "CHEVROLET", model: "EXPRESS PASSENGER VAN" },
    { brand: "CHEVROLET", model: "EXR" },
    { brand: "CHEVROLET", model: "EXZ" },
    { brand: "CHEVROLET", model: "FVR" },
    { brand: "CHEVROLET", model: "FVR 23G" },
    { brand: "CHEVROLET", model: "FVR 32" },
    { brand: "CHEVROLET", model: "FVR 33K" },
    { brand: "CHEVROLET", model: "GMC YUKON" },
    { brand: "CHEVROLET", model: "GRAND AM" },
    { brand: "CHEVROLET", model: "GRAND BLAZER" },
    { brand: "CHEVROLET", model: "GRAND BLAZER Z71" },
    { brand: "CHEVROLET", model: "GRAND VITARA" },
    { brand: "CHEVROLET", model: "GRAND VITARA XL7" },
    { brand: "CHEVROLET", model: "IMPALA" },
    { brand: "CHEVROLET", model: "JIMNY" },
    { brand: "CHEVROLET", model: "KODIAK 6500" },
    { brand: "CHEVROLET", model: "KODIAK 7500" },
    { brand: "CHEVROLET", model: "KODIAK 8500" },
    { brand: "CHEVROLET", model: "LUMINA" },
    { brand: "CHEVROLET", model: "LUMINA APV" },
    { brand: "CHEVROLET", model: "LUV" },
    { brand: "CHEVROLET", model: "LUV  D-MAX" },
    { brand: "CHEVROLET", model: "MALIBU" },
    { brand: "CHEVROLET", model: "MERIVA" },
    { brand: "CHEVROLET", model: "MONTANA" },
    { brand: "CHEVROLET", model: "MONTE CARLO" },
    { brand: "CHEVROLET", model: "MONZA" },
    { brand: "CHEVROLET", model: "NKR / NHR" },
    { brand: "CHEVROLET", model: "NOVA" },
    { brand: "CHEVROLET", model: "NPR" },
    { brand: "CHEVROLET", model: "NPR 66L" },
    { brand: "CHEVROLET", model: "NPR 71L" },
    { brand: "CHEVROLET", model: "OPTRA" },
    { brand: "CHEVROLET", model: "ORLANDO" },
    { brand: "CHEVROLET", model: "P31" },
    { brand: "CHEVROLET", model: "P31 238" },
    { brand: "CHEVROLET", model: "P31 292" },
    { brand: "CHEVROLET", model: "P31 350" },
    { brand: "CHEVROLET", model: "PICK-UP  S10" },
    { brand: "CHEVROLET", model: "PICK-UP C10" },
    { brand: "CHEVROLET", model: "PICK-UP C1500" },
    { brand: "CHEVROLET", model: "PICK-UP C-1500 CHEYENNE" },
    { brand: "CHEVROLET", model: "S. BRIGADIER" },
    { brand: "CHEVROLET", model: "SAFARI" },
    { brand: "CHEVROLET", model: "SILVERADO" },
    { brand: "CHEVROLET", model: "SPARK" },
    { brand: "CHEVROLET", model: "SUBURBAN" },
    { brand: "CHEVROLET", model: "SUNFIRE" },
    { brand: "CHEVROLET", model: "SUNFIRE GT" },
    { brand: "CHEVROLET", model: "SUPER CARRY" },
    { brand: "CHEVROLET", model: "SWIFT" },
    { brand: "CHEVROLET", model: "TAHOE" },
    { brand: "CHEVROLET", model: "TRAILBLAZER" },
    { brand: "CHEVROLET", model: "VITARA" },
    { brand: "CHEVROLET", model: "WAGON R+" },
    { brand: "CHRYSLER", model: "300C" },
    { brand: "CHRYSLER", model: "300M" },
    { brand: "CHRYSLER", model: "BYD FLYER" },
    { brand: "CHRYSLER", model: "CIRRUS" },
    { brand: "CHRYSLER", model: "LE BARON" },
    { brand: "CHRYSLER", model: "NEON" },
    { brand: "CHRYSLER", model: "NEW YORKER" },
    { brand: "CHRYSLER", model: "PT CRUISER" },
    { brand: "CHRYSLER", model: "SEBRING" },
    { brand: "CHRYSLER", model: "VALIANT" },
    { brand: "CHRYSLER", model: "VAN TOWN-COUNTRY" },
    { brand: "CINASCAR", model: "CHANA DOBLE CABINA" },
    { brand: "CINASCAR", model: "CHANA PICK UP" },
    { brand: "CINASCAR", model: "HAFEI  LOBO" },
    { brand: "CINASCAR", model: "HAFEI XINYI" },
    { brand: "CINASCAR", model: "HAFEI ZHONGHIL" },
    { brand: "CINASCAR", model: "SAIC WULING CARGO PANEL VAN" },
    { brand: "CINASCAR", model: "SAIC WULING SUPER VAN CONFORT" },
    { brand: "CINASCAR", model: "ZOTYE NOMAD" },
    { brand: "CINASCAR", model: "ZX AUTO GRAND TIGER" },
    { brand: "CITROEN", model: "BERLINGO" },
    { brand: "CITROEN", model: "C2 VTR" },
    { brand: "CITROEN", model: "C3" },
    { brand: "CITROEN", model: "C4  COUPE  VTS" },
    { brand: "CITROEN", model: "C4 BERLINA" },
    { brand: "CITROEN", model: "C5" },
    { brand: "CITROEN", model: "PICASSO XSARA" },
    { brand: "DACIA", model: "BERLINA" },
    { brand: "DACIA", model: "BREAK" },
    { brand: "DACIA", model: "NOVA" },
    { brand: "DAEWOO", model: "CIELO" },
    { brand: "DAEWOO", model: "DAMAS" },
    { brand: "DAEWOO", model: "ESPERO" },
    { brand: "DAEWOO", model: "LABO" },
    { brand: "DAEWOO", model: "LANOS" },
    { brand: "DAEWOO", model: "LEGANZA" },
    { brand: "DAEWOO", model: "MATIZ" },
    { brand: "DAEWOO", model: "NUBIRA" },
    { brand: "DAEWOO", model: "PRINCE" },
    { brand: "DAEWOO", model: "RACER" },
    { brand: "DAEWOO", model: "RACER CAB." },
    { brand: "DAEWOO", model: "SUPER SALOON" },
    { brand: "DAEWOO", model: "TACUMA" },
    { brand: "DAEWOO", model: "TICO" },
    { brand: "DAIHATSU", model: "APPLAUSE" },
    { brand: "DAIHATSU", model: "CHARADE" },
    { brand: "DAIHATSU", model: "FEROZA" },
    { brand: "DAIHATSU", model: "TERIOS" },
    { brand: "DAIHATSU", model: "TERIOS  BE-GO" },
    { brand: "DODGE", model: "ASPEN" },
    { brand: "DODGE", model: "B200 TRADESMAN" },
    { brand: "DODGE", model: "B300 TRADESMAN" },
    { brand: "DODGE", model: "B400" },
    { brand: "DODGE", model: "B500" },
    { brand: "DODGE", model: "B600" },
    { brand: "DODGE", model: "B700" },
    { brand: "DODGE", model: "BRISA (Accent)" },
    { brand: "DODGE", model: "BRISA (Getz)" },
    { brand: "DODGE", model: "CALIBER" },
    { brand: "DODGE", model: "CAMION 350" },
    { brand: "DODGE", model: "CAMION 600" },
    { brand: "DODGE", model: "CARAVAN" },
    { brand: "DODGE", model: "DAKOTA" },
    { brand: "DODGE", model: "DART" },
    { brand: "DODGE", model: "DAYTONA" },
    { brand: "DODGE", model: "DURANGO" },
    { brand: "DODGE", model: "FORZA" },
    { brand: "DODGE", model: "GRAND CARAVAN" },
    { brand: "DODGE", model: "INTREPID" },
    { brand: "DODGE", model: "MAXI WAGON" },
    { brand: "DODGE", model: "RAM 2500" },
    { brand: "DODGE", model: "RAM 3500" },
    { brand: "DODGE", model: "RAM 4500" },
    { brand: "DODGE", model: "SPIRIT" },
    { brand: "DODGE", model: "STEALTH" },
    { brand: "DODGE", model: "STRATUS" },
    { brand: "DODGE", model: "VIPER" },
    { brand: "DONGFENG", model: "	RICH P11" },
    { brand: "DONGFENG", model: "CAPTAIN C DF1114" },
    { brand: "DONGFENG", model: "DOULIKA 7T" },
    { brand: "DONGFENG", model: "DUOLIKA 5T" },
    { brand: "DONGFENG", model: "PICK UP DC 4X4" },
    { brand: "DONGFENG", model: "RICH 6" },
    { brand: "DONGFENG", model: "RICH 6 Diesel" },
    { brand: "DONGFENG", model: "S30" },
    { brand: "EBRO", model: "60" },
    { brand: "EBRO", model: "85/7DT (100/8D)" },
    { brand: "EBRO", model: "AV3500" },
    { brand: "ENCAVA", model: "410" },
    { brand: "ENCAVA", model: "E1000 49A" },
    { brand: "ENCAVA", model: "E2000" },
    { brand: "ENCAVA", model: "E3000" },
    { brand: "ENCAVA", model: "E3100" },
    { brand: "ENCAVA", model: "E510" },
    { brand: "ENCAVA", model: "E600" },
    { brand: "ENCAVA", model: "E610" },
    { brand: "ENCAVA", model: "E700" },
    { brand: "ENCAVA", model: "ENT3200" },
    { brand: "ENCAVA", model: "ENT3300" },
    { brand: "ENCAVA", model: "ENT6000" },
    { brand: "ENCAVA", model: "ENT610" },
    { brand: "ENCAVA", model: "ENT6100" },
    { brand: "ENCAVA", model: "ENT900" },
    { brand: "ENCAVA", model: "ET5" },
    { brand: "ENCAVA", model: "PROTB74 / A37" },
    { brand: "ENCAVA", model: "PROTB74 / A37 TRS" },
    { brand: "ENCAVA", model: "PROTB74 / A37 TRS " },
    { brand: "FIAT", model: "124" },
    { brand: "FIAT", model: "125" },
    { brand: "FIAT", model: "128" },
    { brand: "FIAT", model: "131" },
    { brand: "FIAT", model: "132" },
    { brand: "FIAT", model: "147" },
    { brand: "FIAT", model: "682/N3" },
    { brand: "FIAT", model: "682/T3" },
    { brand: "FIAT", model: "693/N7" },
    { brand: "FIAT", model: "693/T3" },
    { brand: "FIAT", model: "ARGO TREKKING" },
    { brand: "FIAT", model: "BRAVA" },
    { brand: "FIAT", model: "CRONOS CVT" },
    { brand: "FIAT", model: "CRONOS MT" },
    { brand: "FIAT", model: "FIORINO" },
    { brand: "FIAT", model: "FULLBACK Diesel" },
    { brand: "FIAT", model: "IDEA HLX / AVENTURE / SKY" },
    { brand: "FIAT", model: "MAREA ELX /  WEEKEND" },
    { brand: "FIAT", model: "MIRAFIORI" },
    { brand: "FIAT", model: "MOBI TREKKING" },
    { brand: "FIAT", model: "PALIO" },
    { brand: "FIAT", model: "PALIO ADVENTURE/HLX/WEEKEND" },
    { brand: "FIAT", model: "PALIO FIRE" },
    { brand: "FIAT", model: "PALIO MPI" },
    { brand: "FIAT", model: "PICK-UP STRADA TREKKING" },
    { brand: "FIAT", model: "PICK-UP STRADA TREKKING MPI" },
    { brand: "FIAT", model: "PREMIO" },
    { brand: "FIAT", model: "PUNTO" },
    { brand: "FIAT", model: "REGATA" },
    { brand: "FIAT", model: "RITMO" },
    { brand: "FIAT", model: "SELECTA" },
    { brand: "FIAT", model: "SIENA" },
    { brand: "FIAT", model: "SIENA FIRE" },
    { brand: "FIAT", model: "SIENA HLX" },
    { brand: "FIAT", model: "SPAZIO" },
    { brand: "FIAT", model: "STYLO" },
    { brand: "FIAT", model: "TEMPRA" },
    { brand: "FIAT", model: "TIPO" },
    { brand: "FIAT", model: "TUCAN" },
    { brand: "FIAT", model: "UNO" },
    { brand: "FIAT", model: "UNO FIRE" },
    { brand: "FIATAGRI", model: "TRACTOR GRIMANSA 130-90" },
    { brand: "FIATAGRI", model: "TRACTOR GRIMANSA 160-90" },
    { brand: "FORD", model: "AEROSTAR" },
    { brand: "FORD", model: "B350" },
    { brand: "FORD", model: "B600" },
    { brand: "FORD", model: "B750" },
    { brand: "FORD", model: "BRONCO" },
    { brand: "FORD", model: "BRONCO SPORT" },
    { brand: "FORD", model: "CARGO 1617" },
    { brand: "FORD", model: "CARGO 1721" },
    { brand: "FORD", model: "CARGO 1722" },
    { brand: "FORD", model: "CARGO 1730" },
    { brand: "FORD", model: "CARGO 2632" },
    { brand: "FORD", model: "CARGO 4432" },
    { brand: "FORD", model: "CARGO 4532" },
    { brand: "FORD", model: "CARGO 815" },
    { brand: "FORD", model: "CARGO 915" },
    { brand: "FORD", model: "CONQUISTADOR" },
    { brand: "FORD", model: "CONTINENTAL" },
    { brand: "FORD", model: "CORCEL GHIA / DEL REY" },
    { brand: "FORD", model: "CORCEL II / DEL REY" },
    { brand: "FORD", model: "COUGAR" },
    { brand: "FORD", model: "CROWN VICTORIA" },
    { brand: "FORD", model: "ECONOLINE" },
    { brand: "FORD", model: "ECOSPORT" },
    { brand: "FORD", model: "ESCAPE" },
    { brand: "FORD", model: "ESCORT" },
    { brand: "FORD", model: "ESCORT/ORION (116)" },
    { brand: "FORD", model: "EXCURSION" },
    { brand: "FORD", model: "EXPEDITION" },
    { brand: "FORD", model: "EXPLORER" },
    { brand: "FORD", model: "EXPLORER SPORT" },
    { brand: "FORD", model: "EXPLORER SPORT TRAC" },
    { brand: "FORD", model: "EXPLORER ST" },
    { brand: "FORD", model: "F-100" },
    { brand: "FORD", model: "F-150" },
    { brand: "FORD", model: "F-150  FX4 / Harley Davidson" },
    { brand: "FORD", model: "F-150  RAPTOR" },
    { brand: "FORD", model: "F-250 Super Duty" },
    { brand: "FORD", model: "F-350" },
    { brand: "FORD", model: "F350 DIESEL" },
    { brand: "FORD", model: "F-350 Super Duty" },
    { brand: "FORD", model: "F600" },
    { brand: "FORD", model: "F650" },
    { brand: "FORD", model: "F7000" },
    { brand: "FORD", model: "F750" },
    { brand: "FORD", model: "F800" },
    { brand: "FORD", model: "F8000" },
    { brand: "FORD", model: "F9000 GURI" },
    { brand: "FORD", model: "FAIRLANE" },
    { brand: "FORD", model: "FAIRLANE 500 / GALAXIE" },
    { brand: "FORD", model: "FAIRMONT" },
    { brand: "FORD", model: "FALCON" },
    { brand: "FORD", model: "FESTIVA" },
    { brand: "FORD", model: "FIESTA" },
    { brand: "FORD", model: "FIESTA MAX" },
    { brand: "FORD", model: "FIESTA MOVE" },
    { brand: "FORD", model: "FIESTA POWER" },
    { brand: "FORD", model: "FIESTA TITANIUM" },
    { brand: "FORD", model: "FOCUS" },
    { brand: "FORD", model: "FUSION" },
    { brand: "FORD", model: "FUTURA" },
    { brand: "FORD", model: "GRANADA" },
    { brand: "FORD", model: "GRAND MARQUIS" },
    { brand: "FORD", model: "KA" },
    { brand: "FORD", model: "L8000" },
    { brand: "FORD", model: "L9000" },
    { brand: "FORD", model: "LASER" },
    { brand: "FORD", model: "LINCOLN TOWN CAR" },
    { brand: "FORD", model: "LN8000" },
    { brand: "FORD", model: "LN9000" },
    { brand: "FORD", model: "LTD" },
    { brand: "FORD", model: "MAVERICK" },
    { brand: "FORD", model: "MUSTANG" },
    { brand: "FORD", model: "MUSTANG GT" },
    { brand: "FORD", model: "PROBE" },
    { brand: "FORD", model: "RANGER" },
    { brand: "FORD", model: "RANGER " },
    { brand: "FORD", model: "SIERRA 280" },
    { brand: "FORD", model: "SIERRA 300 / XR4i" },
    { brand: "FORD", model: "TAURUS" },
    { brand: "FORD", model: "TERRITORY" },
    { brand: "FORD", model: "THUNDERBIRD" },
    { brand: "FORD", model: "TRACER" },
    { brand: "FORD", model: "TRACTOR 5000" },
    { brand: "FORD", model: "TRACTOR 6600" },
    { brand: "FORD", model: "TRACTOR 6610" },
    { brand: "FORD", model: "TRACTOR 7610" },
    { brand: "FORD", model: "TRACTOR 8600" },
    { brand: "FORD", model: "TRACTOR TW25" },
    { brand: "FORD", model: "TRACTOR TW30" },
    { brand: "FORD", model: "TRACTOR TW35" },
    { brand: "FORD", model: "WINDSTAR" },
    { brand: "FORD", model: "ZEPHYR" },
    { brand: "FOTON", model: "AUMAN BJ1166VMPHG" },
    { brand: "FOTON", model: "AUMAN BJ4183 ETX1834" },
    { brand: "FOTON", model: "AUMAN ETX 2538" },
    { brand: "FOTON", model: "AUMAN GTL2540" },
    { brand: "FOTON", model: "AUMARK BJ1065VDJD6" },
    { brand: "FOTON", model: "TM 5H (BJ1030V6)" },
    { brand: "FREIGHTLINER", model: "COLUMBIA" },
    { brand: "FREIGHTLINER", model: "COLUMBIA CL" },
    { brand: "FREIGHTLINER", model: "COLUMBIA CL120" },
    { brand: "FREIGHTLINER", model: "FL 112, FLD 112" },
    { brand: "FREIGHTLINER", model: "FLD 120" },
    { brand: "FREIGHTLINER", model: "M2106" },
    { brand: "FREIGHTLINER", model: "M2112" },
    { brand: "GEELY", model: "CK" },
    { brand: "GEELY", model: "HA" },
    { brand: "GEELY", model: "MK" },
    { brand: "GREAT WALL", model: "DEER" },
    { brand: "GREAT WALL", model: "HOVER CUV" },
    { brand: "GREAT WALL", model: "SAFE" },
    { brand: "GREAT WALL", model: "SAILOR" },
    { brand: "GURI", model: "LS8/167" },
    { brand: "GURI", model: "LS8/185" },
    { brand: "GURI", model: "LS8/203" },
    { brand: "GURI", model: "LS9/167" },
    { brand: "GURI", model: "LS9/203" },
    { brand: "GURI", model: "LS9/240" },
    { brand: "GURI", model: "LTS9167" },
    { brand: "GURI", model: "LTS9203" },
    { brand: "GURI", model: "LTS9240" },
    { brand: "HAIMA", model: "7" },
    { brand: "HINO", model: "300" },
    { brand: "HINO", model: "500" },
    { brand: "HINO", model: "DUTRO 300" },
    { brand: "HITACHI", model: "EXCAVADORA EX200" },
    { brand: "HITACHI", model: "EXCAVADORA UH083LC" },
    { brand: "HONDA", model: "ACCORD" },
    { brand: "HONDA", model: "CIVIC" },
    { brand: "HONDA", model: "CIVIC Si" },
    { brand: "HONDA", model: "CR-V" },
    { brand: "HONDA", model: "FIT" },
    { brand: "HONDA", model: "INTEGRA" },
    { brand: "HONDA", model: "LEGEND" },
    { brand: "HONDA", model: "ODYSSEY" },
    { brand: "HONDA", model: "PILOT" },
    { brand: "HONDA", model: "PRELUDE" },
    { brand: "HUMMER", model: "H2" },
    { brand: "HUMMER", model: "H3" },
    { brand: "HYUNDAI", model: "ACCENT" },
    { brand: "HYUNDAI", model: "ATOS GLS" },
    { brand: "HYUNDAI", model: "AZERA" },
    { brand: "HYUNDAI", model: "COUPE TIBURON" },
    { brand: "HYUNDAI", model: "ELANTRA" },
    { brand: "HYUNDAI", model: "EXCAVADORA HL770-7A" },
    { brand: "HYUNDAI", model: "EXCAVADORA R210LC-7" },
    { brand: "HYUNDAI", model: "EXCAVADORA R320LC-7" },
    { brand: "HYUNDAI", model: "EXCEL" },
    { brand: "HYUNDAI", model: "GALLOPER" },
    { brand: "HYUNDAI", model: "GETZ" },
    { brand: "HYUNDAI", model: "H1" },
    { brand: "HYUNDAI", model: "H100" },
    { brand: "HYUNDAI", model: "HD120" },
    { brand: "HYUNDAI", model: "HD65" },
    { brand: "HYUNDAI", model: "HD72" },
    { brand: "HYUNDAI", model: "HD78" },
    { brand: "HYUNDAI", model: "MATRIX" },
    { brand: "HYUNDAI", model: "MIGTHY EX8" },
    { brand: "HYUNDAI", model: "SANTA FE" },
    { brand: "HYUNDAI", model: "SCOUPE LS" },
    { brand: "HYUNDAI", model: "SONATA" },
    { brand: "HYUNDAI", model: "TUCSON" },
    { brand: "HYUNDAI", model: "VERACRUZ" },
    { brand: "HYUNDAI", model: "VERNA" },
    { brand: "IHC HARVESTER", model: "TRACTOR 1066" },
    { brand: "IHC HARVESTER", model: "TRACTOR 1466" },
    { brand: "IHC HARVESTER", model: "TRACTOR 1468" },
    { brand: "IHC HARVESTER", model: "TRACTOR 706" },
    { brand: "IHC HARVESTER", model: "TRACTOR 706D" },
    { brand: "IHC HARVESTER", model: "TRACTOR 766" },
    { brand: "IHC HARVESTER", model: "TRACTOR 826D" },
    { brand: "IHC HARVESTER", model: "TRACTOR 856" },
    { brand: "INTERNATIONAL", model: "1700" },
    { brand: "INTERNATIONAL", model: "1750" },
    { brand: "INTERNATIONAL", model: "1754" },
    { brand: "INTERNATIONAL", model: "1800" },
    { brand: "INTERNATIONAL", model: "1850" },
    { brand: "INTERNATIONAL", model: "1854" },
    { brand: "INTERNATIONAL", model: "1954" },
    { brand: "INTERNATIONAL", model: "2574" },
    { brand: "INTERNATIONAL", model: "4300" },
    { brand: "INTERNATIONAL", model: "4400" },
    { brand: "INTERNATIONAL", model: "4700" },
    { brand: "INTERNATIONAL", model: "5000" },
    { brand: "INTERNATIONAL", model: "5070" },
    { brand: "INTERNATIONAL", model: "7400" },
    { brand: "INTERNATIONAL", model: "7600" },
    { brand: "INTERNATIONAL", model: "8100" },
    { brand: "INTERNATIONAL", model: "9200" },
    { brand: "INTERNATIONAL", model: "9400" },
    { brand: "INTERNATIONAL", model: "3000 BUS" },
    { brand: "INTERNATIONAL", model: "4400 Durastar" },
    { brand: "INTERNATIONAL", model: "7600 Workstar" },
    { brand: "INTERNATIONAL", model: "CF500 / 600" },
    { brand: "ISUZU", model: "AMIGO" },
    { brand: "ISUZU", model: "CARIBE 442" },
    { brand: "ISUZU", model: "FVR" },
    { brand: "ISUZU", model: "GIGA VC61" },
    { brand: "ISUZU", model: "RODEO" },
    { brand: "ISUZU", model: "STYLUS" },
    { brand: "ISUZU", model: "TROOPER" },
    { brand: "IVECO", model: "619" },
    { brand: "IVECO", model: "643" },
    { brand: "IVECO", model: "110.17" },
    { brand: "IVECO", model: "330 PN" },
    { brand: "IVECO", model: "Daily 40.12" },
    { brand: "IVECO", model: "Daily 60.12" },
    { brand: "IVECO", model: "EUROCARGO 120E15" },
    { brand: "IVECO", model: "EUROCARGO 120E18" },
    { brand: "IVECO", model: "EUROCARGO 150E21" },
    { brand: "IVECO", model: "EUROCARGO 150E27H" },
    { brand: "IVECO", model: "EUROCARGO 190E31" },
    { brand: "IVECO", model: "EUROCARGO 190E37H" },
    { brand: "IVECO", model: "EUROCARGO 440E34T" },
    { brand: "IVECO", model: "EUROCARGO 440E35" },
    { brand: "IVECO", model: "EUROCARGO 440E38" },
    { brand: "IVECO", model: "EUROCARGO 450E27T" },
    { brand: "IVECO", model: "EUROCARGO 720E42HT" },
    { brand: "IVECO", model: "EUROCARGO 740E42" },
    { brand: "IVECO", model: "EUROCARGO CAVALLINO 180E32" },
    { brand: "IVECO", model: "EUROCARGO CAVALLINO 450E32" },
    { brand: "IVECO", model: "EUROCARGO TECTOR 170E22" },
    { brand: "IVECO", model: "EUROTECH 440E" },
    { brand: "IVECO", model: "EUROTECH 450E37T" },
    { brand: "IVECO", model: "EUROTRAKKER 380E37" },
    { brand: "IVECO", model: "EUROTRAKKER 400E37HT" },
    { brand: "IVECO", model: "EUROTRAKKER 450E37HT" },
    { brand: "IVECO", model: "NEW DAILY 70C16" },
    { brand: "IVECO", model: "POWER DAILY A42.13 / 50.13" },
    { brand: "IVECO", model: "SCUDATO 40.10" },
    { brand: "IVECO", model: "SCUDATO 59.12" },
    { brand: "IVECO", model: "STRALIS HD 200S38" },
    { brand: "IVECO", model: "STRALIS HD 490S32T" },
    { brand: "IVECO", model: "STRALIS HD 570S42T" },
    { brand: "IVECO", model: "STRALIS HD 740S42T" },
    { brand: "IVECO", model: "TRAKKER 380T38" },
    { brand: "IVECO", model: "TRAKKER 720T42" },
    { brand: "IVECO", model: "TURBO Daily 40.10 / 40.12" },
    { brand: "IVECO", model: "TURBO Daily 59.12" },
    { brand: "IVECO", model: "TURBO Daily 60.12" },
    { brand: "IVECO", model: "VERTIS 130V18" },
    { brand: "IVECO", model: "VERTIS 90V16" },
    { brand: "JAC", model: "HFC1035" },
    { brand: "JAC", model: "HFC1040" },
    { brand: "JAC", model: "HFC1042KN" },
    { brand: "JAC", model: "HFC1045" },
    { brand: "JAC", model: "HFC1061" },
    { brand: "JAC", model: "HFC1063" },
    { brand: "JAC", model: "HFC1071L1K" },
    { brand: "JAC", model: "HFC1083" },
    { brand: "JAC", model: "HFC1131" },
    { brand: "JAC", model: "HFC1131KR1" },
    { brand: "JAC", model: "HFC3130" },
    { brand: "JAC", model: "HFC3252" },
    { brand: "JAC", model: "HFC4250" },
    { brand: "JAC", model: "HFC4251KR1" },
    { brand: "JAC", model: "HFC4253K3R1" },
    { brand: "JAC", model: "J7" },
    { brand: "JAC", model: "JS2 ARENA" },
    { brand: "JAC", model: "JS4 NEVADO" },
    { brand: "JAC", model: "JS6 TEPUY" },
    { brand: "JAC", model: "JS8 SAVANNA" },
    { brand: "JAC", model: "T6 PICK UP" },
    { brand: "JAC", model: "T6 PICK UP DI" },
    { brand: "JAC", model: "T8 PICK UP" },
    { brand: "JEEP", model: "CHEROKEE LIBERTY KJ" },
    { brand: "JEEP", model: "CHEROKEE LIBERTY KK" },
    { brand: "JEEP", model: "CHEROKEE XJ" },
    { brand: "JEEP", model: "CJ-5/7" },
    { brand: "JEEP", model: "CJ-7" },
    { brand: "JEEP", model: "COMANCHE" },
    { brand: "JEEP", model: "COMMANDER" },
    { brand: "JEEP", model: "COMPASS" },
    { brand: "JEEP", model: "GRAND CHEROKEE WJ" },
    { brand: "JEEP", model: "GRAND CHEROKEE WK" },
    { brand: "JEEP", model: "GRAND CHEROKEE WK2" },
    { brand: "JEEP", model: "GRAND CHEROKEE WL" },
    { brand: "JEEP", model: "GRAND CHEROKEE ZJ" },
    { brand: "JEEP", model: "WAGONEER" },
    { brand: "JEEP", model: "WRANGLER" },
    { brand: "JEEP", model: "WRANGLER / RUBICON" },
    { brand: "JEEP", model: "WRANGLER YJ" },
    { brand: "JMC", model: "GRAND AVENUE" },
    { brand: "JMC", model: "JIM REMAX" },
    { brand: "JMC", model: "NEW VIGUS FI" },
    { brand: "JMC", model: "VIGUS PRO FI" },
    { brand: "JOHN DEERE", model: "2130" },
    { brand: "JOHN DEERE", model: "2440" },
    { brand: "JOHN DEERE", model: "3030" },
    { brand: "JOHN DEERE", model: "3350" },
    { brand: "JOHN DEERE", model: "4000" },
    { brand: "JOHN DEERE", model: "4020" },
    { brand: "JOHN DEERE", model: "4050" },
    { brand: "JOHN DEERE", model: "4240" },
    { brand: "JOHN DEERE", model: "4250" },
    { brand: "JOHN DEERE", model: "4440" },
    { brand: "JOHN DEERE", model: "4450" },
    { brand: "JOHN DEERE", model: "4640" },
    { brand: "JOHN DEERE", model: "4650" },
    { brand: "JOHN DEERE", model: "4840" },
    { brand: "JOHN DEERE", model: "5303" },
    { brand: "JOHN DEERE", model: "5403" },
    { brand: "JOHN DEERE", model: "5705" },
    { brand: "JOHN DEERE", model: "6403" },
    { brand: "JOHN DEERE", model: "6505" },
    { brand: "JOHN DEERE", model: "6603" },
    { brand: "JOHN DEERE", model: "6605" },
    { brand: "JOHN DEERE", model: "6615" },
    { brand: "JOHN DEERE", model: "7410" },
    { brand: "JOHN DEERE", model: "7515" },
    { brand: "JOHN DEERE", model: "7810" },
    { brand: "JOHN DEERE", model: "7815" },
    { brand: "JOHN DEERE", model: "8630" },
    { brand: "JOHN DEERE", model: "8650" },
    { brand: "JOHN DEERE", model: "1175 COSECHADORA" },
    { brand: "JOHN DEERE", model: "1450 COSECHADORA" },
    { brand: "JOHN DEERE", model: "1470 COSECHADORA" },
    { brand: "JOHN DEERE", model: "2254 COSECHADORA" },
    { brand: "JOHN DEERE", model: "5090E" },
    { brand: "JOHN DEERE", model: "6110D" },
    { brand: "JOHN DEERE", model: "6125D" },
    { brand: "JOHN DEERE", model: "CARGADOR 624G" },
    { brand: "JOHN DEERE", model: "RETRO EXCAVADORA 310D" },
    { brand: "JOHN DEERE", model: "RETRO EXCAVADORA 310E" },
    { brand: "JOHN DEERE", model: "RETRO EXCAVADORA 310G" },
    { brand: "JOHN DEERE", model: "RETRO EXCAVADORA 410B" },
    { brand: "JOHN DEERE", model: "RETRO EXCAVADORA 410J" },
    { brand: "JOHN DEERE", model: "TRACTOR ORUGA 200LC" },
    { brand: "JOHN DEERE", model: "TRACTOR ORUGA 490E" },
    { brand: "JOHN DEERE", model: "TRACTOR ORUGA 690ELC" },
    { brand: "KAMAZ", model: "4308.1" },
    { brand: "KAMAZ", model: "6460 CHUTO" },
    { brand: "KENWORTH DE LA MONTAÑA", model: "T300" },
    { brand: "KENWORTH DE LA MONTAÑA", model: "T600" },
    { brand: "KENWORTH DE LA MONTAÑA", model: "T800" },
    { brand: "KIA", model: "CARENS" },
    { brand: "KIA", model: "CARNIVAL" },
    { brand: "KIA", model: "CERATO" },
    { brand: "KIA", model: "K 2700" },
    { brand: "KIA", model: "OPIRUS" },
    { brand: "KIA", model: "OPTIMA" },
    { brand: "KIA", model: "PICANTO" },
    { brand: "KIA", model: "PREGIO GS" },
    { brand: "KIA", model: "PREGIO RS" },
    { brand: "KIA", model: "RIO" },
    { brand: "KIA", model: "RIO STYLUS" },
    { brand: "KIA", model: "SEDONA" },
    { brand: "KIA", model: "SEPHIA" },
    { brand: "KIA", model: "SHUMA" },
    { brand: "KIA", model: "SORENTO" },
    { brand: "KIA", model: "SPECTRA" },
    { brand: "KIA", model: "SPORTAGE" },
    { brand: "KOBELCO", model: "EXCAVADORA SK200" },
    { brand: "KOBELCO", model: "EXCAVADORA SK210" },
    { brand: "KOBELCO", model: "EXCAVADORA SK220LC" },
    { brand: "KOBELCO", model: "EXCAVADORA SK250LC" },
    { brand: "KOMATSU", model: "CAMION HM300-2" },
    { brand: "KOMATSU", model: "CARGADOR WA300-3" },
    { brand: "KOMATSU", model: "CARGADOR WA380-1" },
    { brand: "KOMATSU", model: "CARGADOR WA450-1" },
    { brand: "KOMATSU", model: "CARGADOR WA600-3" },
    { brand: "KOMATSU", model: "EXCAVADORA PC100-6" },
    { brand: "KOMATSU", model: "EXCAVADORA PC210" },
    { brand: "KOMATSU", model: "EXCAVADORA PC220-6" },
    { brand: "KOMATSU", model: "GRADERS GD825A-2" },
    { brand: "KOMATSU", model: "MONTACARGAS FD20" },
    { brand: "KOMATSU", model: "TRACTOR  LEGEND 130" },
    { brand: "KOMATSU", model: "TRACTOR 100 GLOBAL FARM" },
    { brand: "KOMATSU", model: "TRACTOR 10000" },
    { brand: "KOMATSU", model: "TRACTOR 110 POWER FARM" },
    { brand: "KOMATSU", model: "TRACTOR 140" },
    { brand: "KOMATSU", model: "TRACTOR 8860" },
    { brand: "KOMATSU", model: "TRACTOR ORUGA D355-A" },
    { brand: "KOMATSU", model: "TRACTOR RDT 14500" },
    { brand: "LADA", model: "MATRIUSHKA" },
    { brand: "LADA", model: "NIVA" },
    { brand: "LADA", model: "SAMARA" },
    { brand: "LAND ROVER", model: "DEFENDER" },
    { brand: "LAND ROVER", model: "DISCOVERY" },
    { brand: "LAND ROVER", model: "FREELANDER" },
    { brand: "LAND ROVER", model: "RANGE ROVER" },
    { brand: "LEXUS", model: "ES300" },
    { brand: "LEXUS", model: "GS350" },
    { brand: "LEXUS", model: "GX460" },
    { brand: "LEXUS", model: "GX470" },
    { brand: "LEXUS", model: "IS250" },
    { brand: "LEXUS", model: "IS300" },
    { brand: "LEXUS", model: "IS350" },
    { brand: "LEXUS", model: "LS400" },
    { brand: "LEXUS", model: "LS430" },
    { brand: "LEXUS", model: "LX470" },
    { brand: "LEXUS", model: "LX570" },
    { brand: "LEXUS", model: "LX600" },
    { brand: "LEXUS", model: "RX300" },
    { brand: "LEXUS", model: "RX350" },
    { brand: "LEXUS", model: "SC300" },
    { brand: "LEXUS", model: "SC400" },
    { brand: "LEXUS", model: "SC430" },
    { brand: "LIEBHERR", model: "GRUA LTL1160" },
    { brand: "LIEBHERR", model: "TRACTOR ORUGA L506" },
    { brand: "LIEBHERR", model: "TRACTOR ORUGA L531" },
    { brand: "LIEBHERR", model: "TRACTOR ORUGA L541" },
    { brand: "LIEBHERR", model: "TRACTOR ORUGA LR632" },
    { brand: "MACK", model: "CH600" },
    { brand: "MACK", model: "CH613" },
    { brand: "MACK", model: "CL700" },
    { brand: "MACK", model: "DM600" },
    { brand: "MACK", model: "DM612" },
    { brand: "MACK", model: "DM686" },
    { brand: "MACK", model: "DM800" },
    { brand: "MACK", model: "DM811" },
    { brand: "MACK", model: "F700" },
    { brand: "MACK", model: "GRANITE CV700" },
    { brand: "MACK", model: "GRANITE GU712, 713" },
    { brand: "MACK", model: "GRANITE GU813" },
    { brand: "MACK", model: "LE613" },
    { brand: "MACK", model: "MC600" },
    { brand: "MACK", model: "MH600" },
    { brand: "MACK", model: "MIDLINER" },
    { brand: "MACK", model: "R400" },
    { brand: "MACK", model: "R600" },
    { brand: "MACK", model: "R686" },
    { brand: "MACK", model: "R700" },
    { brand: "MACK", model: "RD600" },
    { brand: "MACK", model: "RS600" },
    { brand: "MACK", model: "RS700" },
    { brand: "MACK", model: "RW600" },
    { brand: "MACK", model: "RW700" },
    { brand: "MACK", model: "VISION CX,CXN,CXP" },
    { brand: "MACK", model: "VISION CXU" },
    { brand: "MASSEY FERGUSON", model: "680HD" },
    { brand: "MASSEY FERGUSON", model: "COSECHADORA 9895" },
    { brand: "MASSEY FERGUSON", model: "MF1000" },
    { brand: "MASSEY FERGUSON", model: "MF283" },
    { brand: "MASSEY FERGUSON", model: "MF290" },
    { brand: "MASSEY FERGUSON", model: "MF291" },
    { brand: "MASSEY FERGUSON", model: "MF298" },
    { brand: "MASSEY FERGUSON", model: "MF299" },
    { brand: "MASSEY FERGUSON", model: "MF354S" },
    { brand: "MASSEY FERGUSON", model: "MF375" },
    { brand: "MASSEY FERGUSON", model: "MF383" },
    { brand: "MASSEY FERGUSON", model: "MF390" },
    { brand: "MASSEY FERGUSON", model: "MF4265" },
    { brand: "MASSEY FERGUSON", model: "MF4291" },
    { brand: "MASSEY FERGUSON", model: "MF4297" },
    { brand: "MASSEY FERGUSON", model: "MF4299" },
    { brand: "MASSEY FERGUSON", model: "MF-660" },
    { brand: "MASSEY FERGUSON", model: "MF670" },
    { brand: "MAXUS", model: "C300" },
    { brand: "MAXUS", model: "S80 DI" },
    { brand: "MAZ", model: "MASPARRO MV26C016312" },
    { brand: "MAZ", model: "MASPARRO MV26Q016430" },
    { brand: "MAZ", model: "MASPARRO MV27V016501" },
    { brand: "MAZDA", model: "2" },
    { brand: "MAZDA", model: "3" },
    { brand: "MAZDA", model: "5" },
    { brand: "MAZDA", model: "6" },
    { brand: "MAZDA", model: "323" },
    { brand: "MAZDA", model: "626" },
    { brand: "MAZDA", model: "ALLEGRO" },
    { brand: "MAZDA", model: "B-2200" },
    { brand: "MAZDA", model: "B-2300" },
    { brand: "MAZDA", model: "B-2500" },
    { brand: "MAZDA", model: "B-2600" },
    { brand: "MAZDA", model: "B-4000" },
    { brand: "MAZDA", model: "BT-50" },
    { brand: "MAZDA", model: "CX-7" },
    { brand: "MAZDA", model: "CX-9" },
    { brand: "MAZDA", model: "DEMIO" },
    { brand: "MAZDA", model: "MIATA" },
    { brand: "MAZDA", model: "MPV" },
    { brand: "MAZDA", model: "MX-3" },
    { brand: "MAZDA", model: "MX-6" },
    { brand: "MAZDA", model: "PROTEGE LX" },
    { brand: "MERCEDES BENZ", model: "190" },
    { brand: "MERCEDES BENZ", model: "250" },
    { brand: "MERCEDES BENZ", model: "300" },
    { brand: "MERCEDES BENZ", model: "711" },
    { brand: "MERCEDES BENZ", model: "1720" },
    { brand: "MERCEDES BENZ", model: "220 SE/SEB" },
    { brand: "MERCEDES BENZ", model: "220B" },
    { brand: "MERCEDES BENZ", model: "230S" },
    { brand: "MERCEDES BENZ", model: "230SL" },
    { brand: "MERCEDES BENZ", model: "250 SE/SEC/SL" },
    { brand: "MERCEDES BENZ", model: "280SE" },
    { brand: "MERCEDES BENZ", model: "300 E/SEL/SL" },
    { brand: "MERCEDES BENZ", model: "366 CIFERAL" },
    { brand: "MERCEDES BENZ", model: "608D" },
    { brand: "MERCEDES BENZ", model: "ACTROS 3343" },
    { brand: "MERCEDES BENZ", model: "ACTROS 3348" },
    { brand: "MERCEDES BENZ", model: "ACTROS III 3343" },
    { brand: "MERCEDES BENZ", model: "ACTROS III 3348" },
    { brand: "MERCEDES BENZ", model: "ATEGO 1725" },
    { brand: "MERCEDES BENZ", model: "ATEGO 2425" },
    { brand: "MERCEDES BENZ", model: "AXOR II 2640" },
    { brand: "MERCEDES BENZ", model: "C230K" },
    { brand: "MERCEDES BENZ", model: "C240" },
    { brand: "MERCEDES BENZ", model: "C280" },
    { brand: "MERCEDES BENZ", model: "C320" },
    { brand: "MERCEDES BENZ", model: "CLK320" },
    { brand: "MERCEDES BENZ", model: "CLK430" },
    { brand: "MERCEDES BENZ", model: "CLK55" },
    { brand: "MERCEDES BENZ", model: "E220" },
    { brand: "MERCEDES BENZ", model: "E320" },
    { brand: "MERCEDES BENZ", model: "E350" },
    { brand: "MERCEDES BENZ", model: "E430" },
    { brand: "MERCEDES BENZ", model: "E55" },
    { brand: "MERCEDES BENZ", model: "G500" },
    { brand: "MERCEDES BENZ", model: "L1113" },
    { brand: "MERCEDES BENZ", model: "L1924" },
    { brand: "MERCEDES BENZ", model: "L2624" },
    { brand: "MERCEDES BENZ", model: "LO915" },
    { brand: "MERCEDES BENZ", model: "LS1634" },
    { brand: "MERCEDES BENZ", model: "LS1924" },
    { brand: "MERCEDES BENZ", model: "LS2638" },
    { brand: "MERCEDES BENZ", model: "MB140D" },
    { brand: "MERCEDES BENZ", model: "ML230" },
    { brand: "MERCEDES BENZ", model: "ML320" },
    { brand: "MERCEDES BENZ", model: "ML350" },
    { brand: "MERCEDES BENZ", model: "ML430" },
    { brand: "MERCEDES BENZ", model: "ML500" },
    { brand: "MERCEDES BENZ", model: "O302" },
    { brand: "MERCEDES BENZ", model: "O309" },
    { brand: "MERCEDES BENZ", model: "O317" },
    { brand: "MERCEDES BENZ", model: "O371" },
    { brand: "MERCEDES BENZ", model: "O400" },
    { brand: "MERCEDES BENZ", model: "OF1218" },
    { brand: "MERCEDES BENZ", model: "S280" },
    { brand: "MERCEDES BENZ", model: "S320" },
    { brand: "MERCEDES BENZ", model: "SPRINTER 310" },
    { brand: "MERCEDES BENZ", model: "SPRINTER 313/413" },
    { brand: "MINI", model: "MINI CORD  " },
    { brand: "MITSUBISHI", model: "3000 GT" },
    { brand: "MITSUBISHI", model: "CANTER 434" },
    { brand: "MITSUBISHI", model: "CANTER 444" },
    { brand: "MITSUBISHI", model: "CANTER FE 434" },
    { brand: "MITSUBISHI", model: "CANTER FE 444" },
    { brand: "MITSUBISHI", model: "CANTER FE 649 D" },
    { brand: "MITSUBISHI", model: "CANTER FE 649 TD" },
    { brand: "MITSUBISHI", model: "CANTER FE 659 TD" },
    { brand: "MITSUBISHI", model: "CANTER FE 84" },
    { brand: "MITSUBISHI", model: "CANTER FE 85" },
    { brand: "MITSUBISHI", model: "DIAMANTE" },
    { brand: "MITSUBISHI", model: "ECLIPSE" },
    { brand: "MITSUBISHI", model: "EXPO VAN" },
    { brand: "MITSUBISHI", model: "FK 615" },
    { brand: "MITSUBISHI", model: "FK 617" },
    { brand: "MITSUBISHI", model: "FM 617" },
    { brand: "MITSUBISHI", model: "FM 657" },
    { brand: "MITSUBISHI", model: "FP 517" },
    { brand: "MITSUBISHI", model: "FV 517" },
    { brand: "MITSUBISHI", model: "GALANT" },
    { brand: "MITSUBISHI", model: "GRANDIS" },
    { brand: "MITSUBISHI", model: "L-200 PICK UP" },
    { brand: "MITSUBISHI", model: "LANCER" },
    { brand: "MITSUBISHI", model: "MF" },
    { brand: "MITSUBISHI", model: "MIRAGE" },
    { brand: "MITSUBISHI", model: "MONTERO DAKAR" },
    { brand: "MITSUBISHI", model: "MONTERO LIMITED" },
    { brand: "MITSUBISHI", model: "MONTERO SPORT" },
    { brand: "MITSUBISHI", model: "MS" },
    { brand: "MITSUBISHI", model: "MX" },
    { brand: "MITSUBISHI", model: "OUTLANDER" },
    { brand: "MITSUBISHI", model: "PANEL  L-300" },
    { brand: "MITSUBISHI", model: "SIGMA" },
    { brand: "MITSUBISHI", model: "SIGNO" },
    { brand: "MITSUBISHI", model: "SPACE WAGON" },
    { brand: "MITSUBISHI", model: "STAR WAGON" },
    { brand: "MITSUBISHI", model: "WAGON VAN" },
    { brand: "NEW HOLLAND", model: "RETRO EXCAVADORA B95B" },
    { brand: "NEW HOLLAND", model: "TRACTOR 7630" },
    { brand: "NEW HOLLAND", model: "TRACTOR 8030" },
    { brand: "NEW HOLLAND", model: "TRACTOR TM140" },
    { brand: "NEW HOLLAND", model: "TRACTOR TM150" },
    { brand: "NISSAN", model: "240SX" },
    { brand: "NISSAN", model: "300ZX" },
    { brand: "NISSAN", model: "350Z" },
    { brand: "NISSAN", model: "ALTIMA" },
    { brand: "NISSAN", model: "MAXIMA" },
    { brand: "NISSAN", model: "MURANO" },
    { brand: "NISSAN", model: "PATHFINDER" },
    { brand: "NISSAN", model: "PATROL" },
    { brand: "NISSAN", model: "PATROL L/KL-60" },
    { brand: "NISSAN", model: "PICK UP" },
    { brand: "NISSAN", model: "PICK UP FRONTIER" },
    { brand: "NISSAN", model: "PICK UP TITAN" },
    { brand: "NISSAN", model: "QUEST" },
    { brand: "NISSAN", model: "SENTRA" },
    { brand: "NISSAN", model: "TERRANO" },
    { brand: "NISSAN", model: "TIIDA" },
    { brand: "NISSAN", model: "XTERRA" },
    { brand: "NISSAN", model: "X-TRAIL" },
    { brand: "PEGASO", model: "1223" },
    { brand: "PEGASO", model: "5035" },
    { brand: "PEGASO", model: "5036" },
    { brand: "PEGASO", model: "1080C" },
    { brand: "PEGASO", model: "1080CL" },
    { brand: "PEGASO", model: "1088C" },
    { brand: "PEGASO", model: "1089C" },
    { brand: "PEGASO", model: "1217 LC" },
    { brand: "PEGASO", model: "2081C" },
    { brand: "PEGASO", model: "2082C" },
    { brand: "PEGASO", model: "3089C" },
    { brand: "PEGASO", model: "5231.23" },
    { brand: "PEGASO", model: "6424 METROBUS" },
    { brand: "PEUGEOT", model: "306" },
    { brand: "PEUGEOT", model: "307" },
    { brand: "PEUGEOT", model: "407" },
    { brand: "PEUGEOT", model: "408" },
    { brand: "PEUGEOT", model: "607" },
    { brand: "PEUGEOT", model: "206CC" },
    { brand: "PEUGEOT", model: "206RC" },
    { brand: "PEUGEOT", model: "206XR" },
    { brand: "PEUGEOT", model: "207  Compact One Line" },
    { brand: "PEUGEOT", model: "207  Compact Sedan" },
    { brand: "PEUGEOT", model: "EXPERT" },
    { brand: "PEUGEOT", model: "PARTNER" },
    { brand: "RENAULT", model: "CLIO" },
    { brand: "RENAULT", model: "DUSTER" },
    { brand: "RENAULT", model: "FUEGO" },
    { brand: "RENAULT", model: "GALA" },
    { brand: "RENAULT", model: "KANGOO" },
    { brand: "RENAULT", model: "KANGOO EXPRESS" },
    { brand: "RENAULT", model: "KANGOO SPORTWAY" },
    { brand: "RENAULT", model: "KOLEOS" },
    { brand: "RENAULT", model: "LAGUNA" },
    { brand: "RENAULT", model: "LOGAN" },
    { brand: "RENAULT", model: "MEGANE" },
    { brand: "RENAULT", model: "MEGANE II" },
    { brand: "RENAULT", model: "R-11" },
    { brand: "RENAULT", model: "R-12" },
    { brand: "RENAULT", model: "R-16" },
    { brand: "RENAULT", model: "R-18" },
    { brand: "RENAULT", model: "R-19" },
    { brand: "RENAULT", model: "R-21" },
    { brand: "RENAULT", model: "R-30" },
    { brand: "RENAULT", model: "R-5" },
    { brand: "RENAULT", model: "SANDERO" },
    { brand: "RENAULT", model: "SCENIC" },
    { brand: "RENAULT", model: "STEPWAY" },
    { brand: "RENAULT", model: "SYMBOL" },
    { brand: "RENAULT", model: "TWINGO" },
    { brand: "SCANIA", model: "F113HL" },
    { brand: "SCANIA", model: "G410" },
    { brand: "SCANIA", model: "G470" },
    { brand: "SCANIA", model: "K113CL" },
    { brand: "SCANIA", model: "K113TL" },
    { brand: "SCANIA", model: "K124" },
    { brand: "SCANIA", model: "K124EB" },
    { brand: "SCANIA", model: "K420" },
    { brand: "SCANIA", model: "K94" },
    { brand: "SCANIA", model: "L113CL" },
    { brand: "SCANIA", model: "P270" },
    { brand: "SCANIA", model: "R114" },
    { brand: "SCANIA", model: "R124" },
    { brand: "SCANIA", model: "R420" },
    { brand: "SEAT", model: "ALHAMBRA" },
    { brand: "SEAT", model: "ALTEA" },
    { brand: "SEAT", model: "CORDOBA" },
    { brand: "SEAT", model: "IBIZA" },
    { brand: "SEAT", model: "LEON" },
    { brand: "SEAT", model: "LEON FR" },
    { brand: "SEAT", model: "LEON R CUPRA" },
    { brand: "SEAT", model: "TOLEDO" },
    { brand: "SINOTRUCK", model: "HOMAN ZZ1168K" },
    { brand: "SINOTRUCK", model: "HOWO A7" },
    { brand: "SINOTRUCK", model: "HOWO T5G" },
    { brand: "SKODA", model: "FABIA" },
    { brand: "SKODA", model: "OCTAVIA" },
    { brand: "SUBARU", model: "FORESTER" },
    { brand: "SUBARU", model: "IMPREZA" },
    { brand: "SUBARU", model: "IMPREZA RS" },
    { brand: "SUBARU", model: "IMPREZA WRX" },
    { brand: "SUBARU", model: "IMPREZA WRX STI" },
    { brand: "SUBARU", model: "JUSTY GL" },
    { brand: "SUBARU", model: "LEGACY" },
    { brand: "SUBARU", model: "OUTBACK" },
    { brand: "SUBARU", model: "SVX" },
    { brand: "SUBARU", model: "TRIBECA B9" },
    { brand: "SUZUKI", model: "CELERIO" },
    { brand: "SUZUKI", model: "GRAND VITARA" },
    { brand: "SUZUKI", model: "JIMNY" },
    { brand: "SUZUKI", model: "SAMURAI" },
    { brand: "SUZUKI", model: "SIDEKICK JX" },
    { brand: "TATA", model: "INDICA" },
    { brand: "TATA", model: "INDIGO" },
    { brand: "TATA", model: "INDIGO SW" },
    { brand: "TATA", model: "SAFARI" },
    { brand: "TOYOTA", model: "4 RUNNER" },
    { brand: "TOYOTA", model: "AVALON" },
    { brand: "TOYOTA", model: "CAMRY" },
    { brand: "TOYOTA", model: "CELICA" },
    { brand: "TOYOTA", model: "C-HR" },
    { brand: "TOYOTA", model: "COASTER" },
    { brand: "TOYOTA", model: "COROLLA" },
    { brand: "TOYOTA", model: "COROLLA CROSS" },
    { brand: "TOYOTA", model: "COROLLA IMP." },
    { brand: "TOYOTA", model: "DYNA" },
    { brand: "TOYOTA", model: "DYNA TURBO" },
    { brand: "TOYOTA", model: "FJ CRUISER" },
    { brand: "TOYOTA", model: "FJ40" },
    { brand: "TOYOTA", model: "FJ45 PICK UP" },
    { brand: "TOYOTA", model: "FJ55 SAMURAI" },
    { brand: "TOYOTA", model: "FJ60 SAMURAI" },
    { brand: "TOYOTA", model: "FJ62 SAMURAI" },
    { brand: "TOYOTA", model: "FJ70 Macho" },
    { brand: "TOYOTA", model: "FJ75 PICK UP" },
    { brand: "TOYOTA", model: "FORTUNER" },
    { brand: "TOYOTA", model: "FZJ71 Macho" },
    { brand: "TOYOTA", model: "FZJ76 Macho" },
    { brand: "TOYOTA", model: "FZJ79 PICK UP" },
    { brand: "TOYOTA", model: "HIACE" },
    { brand: "TOYOTA", model: "HILUX" },
    { brand: "TOYOTA", model: "LAND CRUISER  FJ55" },
    { brand: "TOYOTA", model: "LAND CRUISER 200" },
    { brand: "TOYOTA", model: "LAND CRUISER 4500 VX / FJ80" },
    { brand: "TOYOTA", model: "MERU" },
    { brand: "TOYOTA", model: "MONTACARGAS 42-5FG25" },
    { brand: "TOYOTA", model: "MONTACARGAS 42-6FGC25" },
    { brand: "TOYOTA", model: "MONTACARGAS 4FD25" },
    { brand: "TOYOTA", model: "MONTACARGAS 7FDU30" },
    { brand: "TOYOTA", model: "MONTACARGAS 7FGCU20/25" },
    { brand: "TOYOTA", model: "MR 2" },
    { brand: "TOYOTA", model: "PASEO" },
    { brand: "TOYOTA", model: "PRADO" },
    { brand: "TOYOTA", model: "PREVIA" },
    { brand: "TOYOTA", model: "RAV 4" },
    { brand: "TOYOTA", model: "SEQUOIA" },
    { brand: "TOYOTA", model: "SIENNA" },
    { brand: "TOYOTA", model: "SKY" },
    { brand: "TOYOTA", model: "STARLET" },
    { brand: "TOYOTA", model: "TACOMA" },
    { brand: "TOYOTA", model: "TERCEL" },
    { brand: "TOYOTA", model: "TERIOS" },
    { brand: "TOYOTA", model: "TERIOS  BE-GO" },
    { brand: "TOYOTA", model: "TUNDRA" },
    { brand: "TOYOTA", model: "YARIS" },
    { brand: "TOYOTA", model: "YARIS BELTA" },
    { brand: "TOYOTA", model: "YARIS CROSS" },
    { brand: "TRACTOVEN", model: "ANT 4135F" },
    { brand: "VALTRA", model: "TRACTOR 800" },
    { brand: "VALTRA", model: "TRACTOR BH-140" },
    { brand: "VENIRAUTO", model: "CENTAURO" },
    { brand: "VENIRAUTO", model: "TURPIAL" },
    { brand: "VOLKSWAGEN", model: "17210 OD" },
    { brand: "VOLKSWAGEN", model: "17240 OT" },
    { brand: "VOLKSWAGEN", model: "18310 OT" },
    { brand: "VOLKSWAGEN", model: "9150 OD" },
    { brand: "VOLKSWAGEN", model: "BORA" },
    { brand: "VOLKSWAGEN", model: "BRASILIA" },
    { brand: "VOLKSWAGEN", model: "CORRADO" },
    { brand: "VOLKSWAGEN", model: "CRAFTER" },
    { brand: "VOLKSWAGEN", model: "CROSSFOX" },
    { brand: "VOLKSWAGEN", model: "ESCARABAJO" },
    { brand: "VOLKSWAGEN", model: "FOX" },
    { brand: "VOLKSWAGEN", model: "GOL" },
    { brand: "VOLKSWAGEN", model: "GOLF" },
    { brand: "VOLKSWAGEN", model: "JETTA" },
    { brand: "VOLKSWAGEN", model: "KOMBI" },
    { brand: "VOLKSWAGEN", model: "NEW BEETLE" },
    { brand: "VOLKSWAGEN", model: "PARATI" },
    { brand: "VOLKSWAGEN", model: "PASSAT" },
    { brand: "VOLKSWAGEN", model: "POLO" },
    { brand: "VOLKSWAGEN", model: "SANTANA" },
    { brand: "VOLKSWAGEN", model: "SAVEIRO" },
    { brand: "VOLKSWAGEN", model: "SPACE FOX" },
    { brand: "VOLKSWAGEN", model: "TITAN 17220" },
    { brand: "VOLKSWAGEN", model: "TITAN 18310" },
    { brand: "VOLKSWAGEN", model: "VENTO" },
    { brand: "VOLVO", model: "740" },
    { brand: "VOLVO", model: "850" },
    { brand: "VOLVO", model: "940" },
    { brand: "VOLVO", model: "960" },
    { brand: "VOLVO", model: "B10M" },
    { brand: "VOLVO", model: "B12" },
    { brand: "VOLVO", model: "B12R" },
    { brand: "VOLVO", model: "B58" },
    { brand: "VOLVO", model: "CARGADOR L270" },
    { brand: "VOLVO", model: "CARGADOR L320" },
    { brand: "VOLVO", model: "CARGADOR L330E" },
    { brand: "VOLVO", model: "CARGADOR L60F" },
    { brand: "VOLVO", model: "EXCAVADORA EC210" },
    { brand: "VOLVO", model: "FH12" },
    { brand: "VOLVO", model: "FH380" },
    { brand: "VOLVO", model: "FH420" },
    { brand: "VOLVO", model: "FH480" },
    { brand: "VOLVO", model: "NH12" },
    { brand: "VOLVO", model: "RETRO EXCAVADORA BL60" },
    { brand: "VOLVO", model: "VM23" },
    { brand: "VOLVO", model: "VM260" },
    { brand: "VOLVO", model: "VM310" },
    { brand: "VOLVO", model: "VM71" },
    { brand: "YUTONG", model: "ZK6100NGA9" },
    { brand: "YUTONG", model: "ZK6118HGA" },
    { brand: "YUTONG", model: "ZK6122H9" },
    { brand: "YUTONG", model: "ZK6146H" },
    { brand: "YUTONG", model: "ZK6180HGH" },
    { brand: "YUTONG", model: "ZK6729D2" },
    { brand: "YUTONG", model: "ZK6752DFA9" },
    { brand: "YUTONG", model: "ZK6831HE" },
    { brand: "YUTONG", model: "ZK6852HG" },
    { brand: "YUTONG", model: "ZK6896HGA" },
];
